### ISSUE TITLE
Virtual scroll content disappear when change tabs

### ISSUE THREAD

**Issue by marceloavf** [bhuh12/vue-router-tab#102]
**Describe the bug**
Hi, I'm having a problem with a component that uses Virtual Scrolling when changing tabs with `vue-router-tab`

**To Reproduce**

1. Wait for the data to load in.
2. Scroll horizontally to activate virtual scroll changes (it also happens when there is a lot of data vertically)
3. Go to another tab (about)
4. Then come back home, you will see it blank, but if you scroll in a little it'll come back.

https://codesandbox.io/s/relaxed-voice-m1hwb?file=/src/components/HelloWorld.vue

**Expected behavior**
Expected to be able to see data even when changing tabs, from where we were.

**Screenshots**
When enters the page:
![image](https://user-images.githubusercontent.com/5435657/104480250-242ea900-55a3-11eb-89a1-0bdf3e7f1375.png)

When changes tab after virtual scrolls actives:
![image](https://user-images.githubusercontent.com/5435657/104480315-37da0f80-55a3-11eb-93f5-2ab7b655a200.png)

**Development Environment (please complete the following information):**

- Node.js:  v12.4.0 - v14
- Vue: v2.6.12
- Vue Router v3.4.9
- **Vue Router Tab** v1.2.3

**Operating Environment (please complete the following information):**

- Device: Desktop
- OS: Ubuntu
- Browser: Chrome
- Version: 87

**Additional context**
If it's not really related to `vue-router-tab`, feel free to close it, thank you.

**Comment by marceloavf** [comment]
One way that I found to bring it back was to call `repaint()` method after it get back from `keep-alive` instance with `activated` lifecycle hook.

**Comment by bhuh12** [comment]
Use the following code to replace the RouterTab component, it can still reproduce the problem.

Frame.vue
```
<keep-alive>
  <router-view />
</keep-alive>
```

RouterTab is based on KeepAlive and RouterView components, so this problem will also exist.

Your solution is correct, RouterTab can still respond to the `activated` hook.
