### ISSUE TITLE
在 ROUTER TAB 右上角 一键清除 所有 TAB

### ISSUE THREAD

**Issue by tarzanking** [bhuh12/vue-router-tab#106]
## 您的需求是否与问题有关？

希望可以在右上角 添加一个 按键 来 reset 所有 的 tab
![image](https://user-images.githubusercontent.com/12784182/108446642-6a111800-7299-11eb-9889-e70d27ec99aa.png)

## 描述你想要的解决方案

可以让使用者更快或更有效率的 一键清除 所有 的 tab 恢复到默认

**Comment by bhuh12** [comment]
可以使用插槽 `end` 添加按钮，然后按钮执行方法 `this.$tabs.reset()`

参考：
[Demo-个性化-插槽](https://bhuh12.gitee.io/vue-router-tab/demo/#/slot/page/1)
[个性化-自定义插槽](https://bhuh12.gitee.io/vue-router-tab/zh/guide/custom/slot.html)
[基础-页签操作-重置页签](https://bhuh12.gitee.io/vue-router-tab/zh/guide/essentials/operate.html#%E9%87%8D%E7%BD%AE%E9%A1%B5%E7%AD%BE)
