### ISSUE TITLE
 Icon not load properly 

### ISSUE THREAD

**Issue by tarzanking** [bhuh12/vue-router-tab#107]
**Describe the bug**
Icon not load properly 
![image](https://user-images.githubusercontent.com/12784182/108452020-bca30200-72a2-11eb-85ba-4cd44b5bdb77.png)

**Comment by bhuh12** [comment]
Please check the class of the font icon

**Comment by tarzanking** [comment]
hi my icon class is icon-user
In router was use icon-user
```

meta: {
            title: 'Page', // tab title
            icon: 'icon-user', // tab icon, optional
            tabClass: 'custom-tab', // custom class, optional
            tips: 'This is a tab', // tab tooltip, optional. defaults to `meta.title`
            key: 'path', // tab cache rule, optional
            closable: false // is tab closable, defaults to `true`
          }
```

**Comment by bhuh12** [comment]
![image](https://user-images.githubusercontent.com/9862292/108586135-6c51a000-7387-11eb-8f4b-f6f29d12dca8.png)
Use the development tool to check whether the class of the icon node matches the style sheet, this seems to be a problem with the style of the font icon.

**Comment by tarzanking** [comment]
After added the font-family into css it work thanks man !!

```
.router-tab__item-icon{
  font-family: 'feather';
}
```
