### ISSUE TITLE
Scroll Behaviour

### ISSUE THREAD

**Issue by mwasigala** [bhuh12/vue-router-tab#108]
I have a list within the tab, i want  to remember the position of the list as i navigate.... please help its urgent
Sorry i didn't see an option to submit a question

**Comment by bhuh12** [comment]
https://router.vuejs.org/guide/advanced/scroll-behavior.html#async-scrolling

**Comment by mwasigala** [comment]
I have done so and it's not working  with router tab when I scroll a list then I navigate to other tab then  return back to the. List it doesn't show from the last position

**Comment by bhuh12** [comment]
Presumably the scroll element is not specified

```
scrollBehavior (to, from, savedPosition) {
   if (to.meta.scrollElement) {
     return {
       selector: to.meta.scrollElement
     }
   }
}
```

Reference:
https://router.vuejs.org/guide/advanced/scroll-behavior.html
https://github.com/vuejs/vue-router/blob/dev/examples/scroll-behavior/app.js

**Comment by mwasigala** [comment]
I think this has all to do with how i define my tabs...  with the :tabs attribute; 
because i have tried it in a normal tabs  without using attributes it works , 
The above solution doesn't help my list is dynamic and list elements are created on fly..,

**Comment by bhuh12** [comment]
Is it the tab list or the content on the page that has the problem with scroll positioning?

**Comment by mwasigala** [comment]
The list content within the tab

**Comment by bhuh12** [comment]
Can you provide screenshots, screen recordings, or  code to reproduce the problem?

**Comment by mwasigala** [comment]
Before navigation

![Screenshot 2021-04-14 235610](https://user-images.githubusercontent.com/20720317/114778185-345e4c00-9d7d-11eb-909b-82fb0de0fd61.png)

After Scrolling
![Screenshot 2021-04-14 235704](https://user-images.githubusercontent.com/20720317/114778302-56f06500-9d7d-11eb-993d-6ef7ee0a3b46.png)

Navigating back to the Tab again
![Screenshot 2021-04-14 235610](https://user-images.githubusercontent.com/20720317/114778360-6cfe2580-9d7d-11eb-9c20-3bc7dbe06a9f.png)



It is as if the page doesn't save the scroll position

**Comment by bhuh12** [comment]
RouterTab does not save the scrolling position of the page, because the 'scrollbehavior' provided by vue-router implements this function.

If the page data will be reloaded when the tab is activated, you may need to implement it yourself

1. When "deactivated", record the scrolling position of the scroll element

2. When "activated", set the recorded scroll position to the scroll element after the page data is updated

**Comment by mwasigala** [comment]
@bhuh12  okay thanks for the info

**Comment by bhuh12** [comment]
`v1.2.6` already supports this feature.

Doc: https://bhuh12.github.io/vue-router-tab/guide/custom/scroll.html
Demo: https://bhuh12.github.io/vue-router-tab/demo/#/page-scroller/

This version provides component syntax hints for the Vetur extension, welcome to update and experience.

![image](https://user-images.githubusercontent.com/9862292/117581336-d4b25100-b12e-11eb-8b09-d424ff0f981d.png)

Changelog: https://bhuh12.github.io/vue-router-tab/guide/changelog.html
