### ISSUE TITLE
httpVueLoader ?

### ISSUE THREAD

**Issue by yanzixiang** [bhuh12/vue-router-tab#109]
how to use this by httpVueLoader ？

**Comment by bhuh12** [comment]
I'm sorry I don't have any experience with `httpVueLoader`, this seems to be a library that loads vue spa files directly through the browser, without webpack compilation.

You can try to introduce RouterTab by cdn:

```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vue-router-tab@1.2.4/dist/lib/vue-router-tab.css" />
<script src="https://cdn.jsdelivr.net/npm/vue-router-tab@1.2.4/dist/lib/vue-router-tab.umd.min.js" />
```

**Comment by yanzixiang** [comment]
thanks.
