### ISSUE TITLE
路由开启mode="history"模式，js报错（不能加载出来）

### ISSUE THREAD

**Issue by xiayoutao** [bhuh12/vue-router-tab#11]

**Comment by bhuh12** [comment]
能贴一下错误信息，并提供重现问题的github仓库吗？

`router-tab` 目前是没支持 Nuxt 服务器端渲染的呢

**Comment by xiayoutao** [comment]
![image](https://user-images.githubusercontent.com/27724587/58074824-c03ebc00-7bd8-11e9-8f21-c98f69f569e2.png)
我就是在你demo上改的，页面第一次加载是没有问题的，点击任意一个页面就会报错
![image](https://user-images.githubusercontent.com/27724587/58074880-e19fa800-7bd8-11e9-8d3a-35c4ee2d4623.png)

**Comment by bhuh12** [comment]
这个是文件加载失败啊，history 模式 需要服务器端渲染支持，你自己确认下打包后的页面js文件路径看看

**Comment by xiayoutao** [comment]
嗯，可以了。谢谢！
