### ISSUE TITLE
Nuxt项目下的默认页签支持得不太好

### ISSUE THREAD

**Issue by MarlonDML** [bhuh12/vue-router-tab#113]
**Is your feature request related to a problem? Please describe.**
设置了默认页签后，只是显示了页签，但页面内容不显示，左边菜单栏中对应标题也未选中，需要手动点击一下，页面才会显示

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bhuh12** [comment]
当前激活的路由是否存在默认页签内？

**Comment by MarlonDML** [comment]
已经解决了
