### ISSUE TITLE
Drag sort feature does not work properly in Firefox

### ISSUE THREAD

**Issue by solodyagin** [bhuh12/vue-router-tab#114]

**Comment by bhuh12** [comment]
Drag and drop in Firefox, and the browser will open a new tab。
Do you mean the problem?

**Comment by solodyagin** [comment]
![hWqAlRc4eX](https://user-images.githubusercontent.com/4740535/112632216-e1ae0600-8e48-11eb-8d4f-9dc37c39f0ce.gif)

**Comment by bhuh12** [comment]
This problem has been fixed in `v1.2.5`
