### ISSUE TITLE
我把您项目在vue3运行的时候，在浏览器报错误

### ISSUE THREAD

**Issue by islomkhon** [bhuh12/vue-router-tab#120]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Development Environment (please complete the following information):**

- Node.js: [e.g. v12.4.0]
- Vue: [e.g. v2.5.22]
- Vue Router [e.g. v3.0.1]
- **Vue Router Tab** [e.g. v0.2.0]

**Operating Environment (please complete the following information):**

- Device: [e.g. Desktop]
- OS: [e.g. Windows 10]
- Browser [e.g. stock browser, Chrome]
- Version [e.g. 75]

**Additional context**
我把您项目在vue3运行的时候，在浏览器报vue-router-tab.umd.min.js?f57d:1 Uncaught (in promise) TypeError: Cannot set property '$tabs' of undefined

**Comment by bhuh12** [comment]
多谢关注，项目暂未支持 Vue3
#101
