### ISSUE TITLE
iframe页签切换，每次会有1个被取消的静态资源请求

### ISSUE THREAD

**Issue by babytutu** [bhuh12/vue-router-tab#126]
## Bug 描述

iframe页签切换，每次会有1个被取消的静态资源请求

## 问题重现

重现行为的步骤：

1. 打开demo，点击【打开“Vue.js”】按钮
https://bhuh12.github.io/vue-router-tab/demo/#/iframe/operate

2、清空控制台中网络数据

3、切换标签页【Iframe 页签】

4、观察控制台，控制台出现1条被canceled的请求`Request URL: https://cn.vuejs.org/`

5、再次切换标签页，每次都会多1条被canceled的请求

## 预期行为

不要出现无用的请求

## 运行环境（请填写以下信息）

- 设备: MAC
- 操作系统: 10.13
- 浏览器和版本:  Chrome 92.0.4515.159 x64

**Comment by bhuh12** [comment]
经调试验证，该问题和 Vue 的列表过渡 `<transition-group>` 有关，使用 `<transition>` 或不使用过渡组件都能避免该问题。

但 iframe 页面切换需要与普通页面切换保持一致的过渡效果，并且 iframe 页签需要支持同时打开多个的场景，故只能继续使用 `<transition-group>` 。

并且该问题并不影响功能使用，暂不解决。

**源代码实现参考**
> https://github.com/bhuh12/vue-router-tab/blob/main/lib/RouterTab.vue#L49
``` html
<!-- iframe 页面 -->
      <transition-group
        v-bind="pageTrans"
        tag="div"
        class="router-tab__iframes"
      >
        <iframe
          v-for="url in iframes"
          v-show="url === currentIframe"
          :key="url"
          :src="url"
          :name="iframeNamePrefix + url"
          frameborder="0"
          class="router-tab__iframe"
          @load="iframeLoaded(url)"
        />
      </transition-group>
    </div>
```

**Comment by babytutu** [comment]
的确如你所说，还特地又试了vue3，transition-group和iframe还是有相同问题，此问题对性能影响较小，只能搁置了，谢谢答复

**Comment by babytutu** [comment]
的确如你所说，还特地又试了vue3，transition-group和iframe还是有相同问题，此问题对性能影响较小，只能搁置了，谢谢答复
