### ISSUE TITLE
需要每次点开都是一个新页签功能

### ISSUE THREAD

**Issue by hellolex** [bhuh12/vue-router-tab#13]
你好，我这里有一个需求是每次点链接都要打开一个新页签，不管是vue组件页面还是iframe页面，不知道在这个插件里要怎么设置呢？
比如说有个链接点击是新增项目页面，然后点一次出现一个新增项目页，再点一次新开一个新增项目页，然后这些打开的页面都会保持自身的数据，在这个页面输入什么切换到另一个页面后回来还是原样，另一个页面也是
还有那种编辑页，比如说id为1的编辑页也是，点击一次出现一个，然后这些多个id为1的编辑页也要数据不串

**Comment by bhuh12** [comment]
针对页面路由配置内置规则 `fullPath` 即可。

参考文档：[页签规则](https://bhuh12.github.io/vue-router-tab/guide/essentials/rule.html#%E5%86%85%E7%BD%AE%E8%A7%84%E5%88%99)

对应的路由 meta 类似这样设置：
``` javascript
const route = {
  path: '/create-page',
  meta: {
    title: '创建页面',
    aliveId: 'fullPath'
  }
}
```

打开新页签的方法
``` javascript
this.$router.push('/create-page?time=' + new Date().getTime())
```

编辑页类似

**Comment by bhuh12** [comment]
请问可以实现你的需求吗？麻烦确认一下

**Comment by hellolex** [comment]
你好，谢谢解答，明白你的意思了，测试了一下，vue组件页面可以成功，iframe页面在iframe的src属性传的地址上加上m=akdjlaj之类的随机变量可以生效
