### ISSUE TITLE
控制台一直报router-link的tag prop警告

### ISSUE THREAD

**Issue by zhang761750981** [bhuh12/vue-router-tab#134]
## Bug 描述

 <router-link>'s tag prop is deprecated and has been removed in Vue Router 4. Use the v-slot API to remove this warning

## 问题重现

重现行为的步骤：

加载一个页面，出现一个页签之后

## 预期行为

控制台无警告信息

## 开发环境（请填写以下信息）

- Vue Router: ^3.5.3

## 运行环境（请填写以下信息）

- 设备: PC
- 操作系统:  Windows 10

**Comment by bhuh12** [comment]
`v1.2.9` 版本已修复该问题，更新试试
