### ISSUE TITLE
Changing 'routeTab' of inactive tab causes activeTab to change

### ISSUE THREAD

**Issue by ithil** [bhuh12/vue-router-tab#135]
**Describe the bug**
When the computed property `routeTab` changes in a background tab the values of `routeTab` are assigned to the `activeTab`. This has the effect that the `activeTab` gets the wrong title but keeps its proper icon.

I believe the problem is here: https://github.com/bhuh12/vue-router-tab/blob/main/lib/mixins/routerPage.js#L32  
The values of routeTab should not be assigned to the activeTab but to the tab with the same `id`.

**Development Environment (please complete the following information):**

- Node.js: [e.g. v16.5.0]
- Vue: [e.g. v2.6.11]
- Vue Router [e.g. v3.2.0]
- **Vue Router Tab** [e.g. v0.2.8]

**Comment by ithil** [comment]
After some experimenting I found a way to fix it here: https://github.com/ithil/vue-router-tab/commit/a5d37ec5886461b37f9b0c00e734ed1383dab6bc

Should I send a pull request?

**Comment by bhuh12** [comment]
> After some experimenting I found a way to fix it here: [ithil@a5d37ec](https://github.com/ithil/vue-router-tab/commit/a5d37ec5886461b37f9b0c00e734ed1383dab6bc)
> 
> Should I send a pull request?

Yes, please.
