### ISSUE TITLE
当 this.$vnode.data.key 不存在时,动态页签无法更新

### ISSUE THREAD

**Issue by VFiee** [bhuh12/vue-router-tab#138]
**Describe the bug**
页面 data 配置动态页签 routeTab:{title:"动态页签"}

源码根据 this.$vnode.data.key动态更新匹配到的页签,但部分页签下没有 this.$vnode.data.key
导致动态页签无法更新

使用最新版的 vue-router-tab 1.2.10

**Comment by bhuh12** [comment]
请更新 `v1.2.11` 试试看是否修复

应该是修复这个问题引发的
#135

**Comment by vfiee** [comment]
恢复成之前的对 [#135](https://github.com/bhuh12/vue-router-tab/issues/135)还有影响么,或者说 135 的问题能解决么?

**Comment by vfiee** [comment]
能否获取一下作者的联系方式,方便沟通,后续再把沟通的问题发布到 github 上

**Comment by bhuh12** [comment]
`v1.2.11` 更新了后问题还没解决吗

**Comment by vfiee** [comment]
更新后貌似没有问题了，继续观察中
