### ISSUE TITLE
使用自定义模板后，iframe页签右上角的关闭按钮无效

### ISSUE THREAD

**Issue by hellolex** [bhuh12/vue-router-tab#14]
使用自定义模板后，iframe页签右上角的关闭按钮无效，使用右键菜单关闭就可以

**Comment by bhuh12** [comment]
已更正文档和Demo，请参考 [文档 - 自定义页签模板](https://bhuh12.github.io/vue-router-tab/guide/advanced/slot.html) 配置 Slot
