### ISSUE TITLE
this.$routerTab is undefined

### ISSUE THREAD

**Issue by firebear-ssl** [bhuh12/vue-router-tab#15]
vue -V是2.9.6
按“https://bhuh12.github.io/vue-router-tab/guide/essentials/”进行了引入，可以正常使用
main.js
// 引入组件和样式
import RouterTab from 'vue-router-tab'
import 'vue-router-tab/dist/lib/vue-router-tab.css'

Vue.config.productionTip = false
Vue.use(RouterTab)

但是在任意组件的vue文件中使用this.$touterTab关键字都是未定义错误，有没有同样问题的？应该如何解决？

**Comment by bhuh12** [comment]
父路由组件内必须包含 `<router-tab>`

- 参考[应用组件](https://bhuh12.github.io/vue-router-tab/guide/essentials/#%E5%BA%94%E7%94%A8%E7%BB%84%E4%BB%B6)，在页签页面的父级路由组件内引入 `<router-tab/>`

- 参考[路由配置](https://bhuh12.github.io/vue-router-tab/guide/essentials/#%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE) 配置路由信息

**Comment by firebear-ssl** [comment]
![图片](https://user-images.githubusercontent.com/22034607/59317150-42139800-8cf4-11e9-8293-d2a66b569e4e.png)
![图片](https://user-images.githubusercontent.com/22034607/59317267-b5b5a500-8cf4-11e9-9d03-6e0573e90f54.png)
确实还是不行。仍然是undefined

**Comment by firebear-ssl** [comment]
不知道能否提供一个示例工程？

**Comment by firebear-ssl** [comment]
1、再次重新试了一下，确保在父路由组件内已经有 <router-tab>。
2、路由配置内也加了。代码如下
`import Vue from 'vue';
import Router from 'vue-router';
import http from '@/utils/httpRequest';
import { isURL } from '@/utils/validate';
import { clearLoginInfo } from '@/utils';
// RouterTab 内置路由
import { RouterTabRoutes } from 'vue-router-tab';

Vue.use(Router);

// 开发环境不使用懒加载, 因为懒加载页面太多的话会造成webpack热更新太慢, 所以只有生产环境使用懒加载
const _import = require('./import-' + process.env.NODE_ENV);

// 全局路由(无需嵌套上左右整体布局)
const globalRoutes = [

  { path: '/404', component: _import('modules/Errors'), name: '404', meta: { title: '404未找到' } },

  { path: '/login', component: _import('common/Login'), name: 'login', meta: { title: '登录' } },

  { path: '/add-new-artcile-open', component: _import('modules/add-new-article'), name: 'add-new-artcile-open', meta: { layout: 'main' } },
  // 引入 RouterTab 内置路由以支持操作 iframe 页签
  ...RouterTabRoutes,
];

// 主入口路由(需嵌套上左右整体布局)
const mainRoutes = {
  path: '/main',
  component: _import('main'),
  name: 'main',
  redirect: { path: '/dashboard' },
  // redirect: { name: 'dashboard' },
  //meta: { title: '主入口整体布局' },
  ...RouterTabRoutes,
  children: [// 孩子必须基于母框架进行加载
    // { path: '/home-overview', name: 'home-overview', component: DashBoard, },
    // { path: '/home-overview2', name: 'home-overview2', component: PersonalBlog, }
    // 引入 RouterTab 内置路由以支持操作 iframe 页签
    ...RouterTabRoutes,
    {
      path: '/user-profile-lite',
      name: 'user-profile-lite',
      component: _import('modules/user-profile-lite'),
      meta: { title: '个人信息', icon: 'fa fa-user' },
    },
    {
      path: '/add-new-artcile',
      name: 'add-new-artcile',
      component: _import('modules/add-new-article'),
      meta: { title: '新建稿件', icon: 'fa fa-user' },
    },
  ],
  beforeEnter (to, from, next) {
    if(to.name != 'login') {
      // Login Status
      let token = Vue.cookie.get('token')
      console.log('user token:' + token)
      if (!token || !/\S/.test(token)) {
        clearLoginInfo()
        next({ name: 'login' })
      }
      next()
    } else {
      next();
    }
  }
};

//
const router = new Router({
  mode: 'history',
  base: process.env.BASE_URL,
  // linkActiveClass: 'active',
  // linkExactActiveClass: 'exact-active',
  isAddDynamicMenuRoutes: false, // 是否已经添加动态(菜单)路由
  scrollBehavior() {
    return { x: 0, y: 0 };
  },
  routes: globalRoutes.concat(mainRoutes),
});

router.beforeEach((to, from, next) => {
  // 添加动态(菜单)路由
  // 1. 已经添加 or 全局路由, 直接访问
  // 2. 获取菜单列表, 添加并保存本地存储
  // console.debug('isAddDynamicMenuRoutes：'+ router.options.isAddDynamicMenuRoutes)
  // console.debug('fnCurrentRouteType：'+ fnCurrentRouteType(to))
  if (router.options.isAddDynamicMenuRoutes || fnCurrentRouteType(to) === 'global') {
    // console.debug('bbbb11111111')
    next()
  } else {
    // console.debug('bbbb22222222')
    http({
      url: http.adornUrl('/sys/menu/nav'),
      method: 'get',
      params: http.adornParams()
    }).then(({data}) => {
      if (data && data.code === 0) {
        fnAddDynamicMenuRoutes(data.menuList)
        router.options.isAddDynamicMenuRoutes = true
        sessionStorage.setItem('menuList', JSON.stringify(data.menuList || '[]'))
        sessionStorage.setItem('permissions', JSON.stringify(data.permissions || '[]'))
        next({ ...to, replace: true })
      } else {
        sessionStorage.setItem('menuList', '[]')
        sessionStorage.setItem('permissions', '[]')
        next()
      }
    }).catch((e) => {
      console.debug(`%c${e} 请求菜单列表和权限失败，跳转至登录页！！`, 'color:blue')
      router.push({ name: 'login' })
    })
  }
})

/**
 * 判断当前路由类型, global: 全局路由, main: 主入口路由
 * @param {*} route 当前路由
 */
function fnCurrentRouteType (route) {
  var temp = []
  for (var i = 0; i < globalRoutes.length; i++) {
    if (route.path === globalRoutes[i].path) {
      return 'global'
    } else if (globalRoutes[i].children && globalRoutes[i].children.length >= 1) {
      temp = temp.concat(globalRoutes[i].children)
    }
  }
  return temp.length >= 1 ? fnCurrentRouteType(route, temp) : 'main'
}

/**
 * 添加动态(菜单)路由
 * @param {*} menuList 菜单列表
 * @param {*} routes 递归创建的动态(菜单)路由
 */
function fnAddDynamicMenuRoutes (menuList = [], routes = []) {
  var temp = []
  for (var i = 0; i < menuList.length; i++) {
    if (menuList[i].list && menuList[i].list.length >= 1) {
      temp = temp.concat(menuList[i].list)
    } else if (menuList[i].url && /\S/.test(menuList[i].url)) {
      menuList[i].url = menuList[i].url.replace(/^\//, '')
      var route = {
        path: '/' + menuList[i].url.replace('/', '-'),
        component: null,
        name: menuList[i].url.replace('/', '-'),
        isAddDynamicMenuRoutes: false,
        meta: {
          menuId: menuList[i].menuId,
          title: menuList[i].name,
          isDynamic: true,
          isTab: true,
          iframeUrl: ''
        }
      }
      // url以http[s]://开头, 通过iframe展示
      if (isURL(menuList[i].url)) {
        route['path'] = `i-${menuList[i].menuId}`
        route['name'] = `i-${menuList[i].menuId}`
        route['meta']['iframeUrl'] = menuList[i].url
      } else {
        try {
          route['component'] = _import(`modules/${menuList[i].url}`) || null;
        } catch (e) {
          console.error(e);
        }
      }
      // console.debug('--------route start--------');
      // console.debug(route);
      // console.debug('--------route end--------');
      routes.push(route);
    }
  }
  if (temp.length >= 1) {
    fnAddDynamicMenuRoutes(temp, routes);
  } else {
    mainRoutes.name = 'main-dynamic';
    mainRoutes.children = routes;
    router.addRoutes([
      mainRoutes,
      { path: '*', redirect: { name: 'login' } },
      // 引入 RouterTab 内置路由以支持操作 iframe 页签
      ...RouterTabRoutes,
    ]);
    sessionStorage.setItem('dynamicMenuRoutes', JSON.stringify(mainRoutes.children || '[]'));
    // console.debug('\n');
    // console.debug('%c!<-------------------- 动态(菜单)路由 s -------------------->', 'color:blue');
    // console.debug(mainRoutes.children);
    // console.debug('%c!<-------------------- 动态(菜单)路由 e -------------------->', 'color:blue');
  }
}

export default router;
`
依然无法使用this.$routerTab,一直报undefined.

**Comment by firebear-ssl** [comment]
![图片](https://user-images.githubusercontent.com/22034607/59321428-8b6be380-8d04-11e9-85a7-a748870b5d8b.png)
是因为VUE CLI不是3的问题吗？

**Comment by bhuh12** [comment]
方法的调用是在生命周期的哪个阶段？可以放到github上重现问题吗？

**Comment by firebear-ssl** [comment]
把工程打了个包，放云盘上了。
链接：https://pan.baidu.com/s/1MQZoU3TQ6StRtveSZ0uZPw 
提取码：mc1g 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by firebear-ssl** [comment]
是在created时候调用的。

**Comment by bhuh12** [comment]
没问题啊，你输出一下 `this`，看是否是 vue 的组件实例

![image](https://user-images.githubusercontent.com/9862292/59358467-327d6900-8d5f-11e9-9bdf-361b54823a60.png)

![image](https://user-images.githubusercontent.com/9862292/59358289-dadefd80-8d5e-11e9-81e9-2ea3750ea9ff.png)

**Comment by firebear-ssl** [comment]
您使用的是node什么版本？

**Comment by bhuh12** [comment]
跟这个应该没关系

1. 先 console 输出 `this` ，看是否 Vue 组件的实例。`$routerTab` 是在 Vue 的原型链上扩展的，要在组件内部才能这样调用。
2. 页面上是否能正常显示页签组件？
3. 重现问题的代码，你要把出错的代码也打包进去啊，我是自己在 created 钩子里面输出的。你也参考我的方式输出看有没问题？

**Comment by firebear-ssl** [comment]
我把node从5升级到8了，一下啥问题都没有了，其它什么都没有调整。
您那边环境能告知一下吗？

**Comment by firebear-ssl** [comment]
谢谢您一路帮助，这个问题还是出来node版本上。
我这边的结论是尽量使用node8,使用最新的vue-loader。

**Comment by bhuh12** [comment]
不好意思啊，没帮上忙。
我的是 `node -v`  **v12.4.0**，`vue -V` **3.8.2**，项目是用 Vue Cli 3 库模式打包的

![image](https://user-images.githubusercontent.com/9862292/59439997-d1ba6300-8e28-11e9-997b-3f09c5c90607.png)

**Comment by firebear-ssl** [comment]
您帮了很大的忙，感谢您制作这个控件。另外您的回复给我了很多思路，我VUE方便还很基础，方便的话加个vx。我的号是firebear

**Comment by bhuh12** [comment]
好啊，可以共同学习进步
