### ISSUE TITLE
页签内路由跳转问题

### ISSUE THREAD

**Issue by ning0825** [bhuh12/vue-router-tab#160]
您好，
比如工程里有a1,a2,b1等路由，a1, a2通过配置相同的meta.key使其在同一个页签内。
我先打开a1，然后从 a1 跳转(push)到 a2，然后打开  b1，再点击页签打开 a2, 这时我调 router.go(-1)，回到了 b1，我期望是回到 a1，请问支持这样么，我在文档里没找到相关内容。

**Comment by bhuh12** [comment]
直接路由跳转到 a1，不要用 router.go(-1)
或者a1 跳转 a2 用 replace

**Comment by ning0825** [comment]
好的，用直接跳转的方式处理了，感谢。
