### ISSUE TITLE
能不能加缓存

### ISSUE THREAD

**Issue by xcsweb** [bhuh12/vue-router-tab#18]
刷新页面后，从缓存数据里面拿到tab标签，包括id那些信息

**Comment by bhuh12** [comment]
是刷新浏览器后还原上次的tab页签列表吗

**Comment by xcsweb** [comment]
对的

**Comment by bhuh12** [comment]
0.2.7 版本已支持浏览器刷新后还原页签
参考文档：[https://bhuh12.github.io/vue-router-tab/guide/advanced/restore.html](https://bhuh12.github.io/vue-router-tab/guide/advanced/restore.html)
