### ISSUE TITLE
设置的多级路由里面的子路由不生效怎么回事

### ISSUE THREAD

**Issue by 17610172271** [bhuh12/vue-router-tab#19]

**Comment by bhuh12** [comment]
能贴下代码实例吗？

**Comment by bhuh12** [comment]
请问问题是否解决呢？

**Comment by linusok** [comment]
我发现一个多级路由的问题：如下图配置：
![image](https://user-images.githubusercontent.com/9760598/62670269-375c4300-b9c5-11e9-8de2-9fe81f3332f7.png)

只要不配那个redirect，就会报下面这个中断。
![image](https://user-images.githubusercontent.com/9760598/62670301-56f36b80-b9c5-11e9-9107-ddb116af3667.png)

**Comment by bhuh12** [comment]
> 我发现一个多级路由的问题：如下图配置：
> ....
> 再补充：redirect如果配置成;redirect:{name:'designer'}，就是把子级路由用name命下名，然后用名字redirect，感觉地址栏里url就乱掉了，点击这个组件后，默认redrect，然后再f5，就变样了，回到首页去了。

不添加redirect，即直接访问 ‘/ide’ 路径，因为这个路径是有 `router-view` 来嵌入子路由页面的（RouterTab 内置），没有子页面填充 router-view 的内容所以未出错。

解决方案：
  不提供 redirect 选项的情况，在子路由 children 里添加与父级路由同名的路由路径 ‘/ide’，并指定需要显示的 component 页面作为默认页签

**Comment by linusok** [comment]
> > 我发现一个多级路由的问题：如下图配置：
> > ....
> > 再补充：redirect如果配置成;redirect:{name:'designer'}，就是把子级路由用name命下名，然后用名字redirect，感觉地址栏里url就乱掉了，点击这个组件后，默认redrect，然后再f5，就变样了，回到首页去了。
> 
> 不添加redirect，即直接访问 ‘/ide’ 路径，因为这个路径是有 `router-view` 来嵌入子路由页面的（RouterTab 内置），没有子页面填充 router-view 的内容所以出错。
> 
> 解决方案：
> 不提供 redirect 选项的情况，在子路由 children 里添加与父级路由同名的路由路径 ‘/ide’，并指定需要显示的 component 页面作为默认页签

首选特别感谢您及时回复！
你说的我也理解，但不建议这样绕开这个问题，因为vue-router本身的应用，也是允许打开某个一级组件后，并不强制要求这个一级组件的子级路由必须提供一个默认的子组件。

您目前这个解决方案确实解决了这个报错问题，但是等于变相强制要求tab要有一个默认tabitem，但是我没有展开工作任务前，就是可能没有tabItem的，再请考虑一下，是否可以解决这个默认不提供tabitem就报中断的问题。

不管如何还是再次感谢你的开源组件给我带来的帮助。

**Comment by bhuh12** [comment]
> > > 我发现一个多级路由的问题：如下图配置：
> > > ....
> 
> 您目前这个解决方案确实解决了这个报错问题，但是等于变相强制要求tab要有一个默认tabitem，但是我没有展开工作任务前，就是可能没有tabItem的，再请考虑一下，是否可以解决这个默认不提供tabitem就报中断的问题。
> 
> 不管如何还是再次感谢你的开源组件给我带来的帮助。

目前 RouterTab 是设计成至少需要一个展示一个页签的。后续会添加配置展示默认内容。不过公司加班严重，近期应该没时间。

方案补充：

你可以尝试在 router-tab 添加 v-if 控制，如果路由是你的默认页面地址就使用原生 router-view，否则使用 router-tab。看能否解决
