### ISSUE TITLE
必须保留一个页签限制，能否去掉

### ISSUE THREAD

**Issue by jackcailj** [bhuh12/vue-router-tab#20]
必须保留一个页签限制，能否去掉或者可配置

**Comment by bhuh12** [comment]
没有页签的情况下，默认显示什么内容呢？
能否把默认显示的内容作为独立的页签，我觉得这样风格也统一一些吧。
不然你还得想办法在关闭最后一个页签的时候显示默认的页签，这个你有好的方案实现吗？

**Comment by jackcailj** [comment]
默认的规则还保留，多出一个配置吧，更灵活，
我想可以定义一个空页面的slot，由使用者来自定义
我现在的需求是允许全部关闭，全部关闭时会显示一个自定义的引导页。

**Comment by bhuh12** [comment]
可以这样实现，不过最近比较忙，没那么快开发。如果等不及的话可以[构建开发版](https://bhuh12.github.io/vue-router-tab/guide/installation.html#%E6%9E%84%E5%BB%BA%E5%BC%80%E5%8F%91%E7%89%88)先自行实现。

当然，也欢迎 Pull request

**Comment by bhuh12** [comment]
1. 配置 `keep-last-tab` 为 `false` 来关闭最后一个页签（[参考](https://bhuh12.github.io/vue-router-tab/api/#keep-last-tab)）
2. 配置 `default-page` 来配置关闭所有页签后跳转的默认页（[参考](https://bhuh12.github.io/vue-router-tab/api/#default-page)）
