### ISSUE TITLE
有根路由“/”报错

### ISSUE THREAD

**Issue by xcsweb** [bhuh12/vue-router-tab#21]
## Bug 描述
针对 bug 清晰简洁的描述。

## 问题重现
重现行为的步骤：
1. 去'...'
2. 点击“...”
3. 向下滚动到“....”
4. 出现"..."错误

## 预期行为
清楚简洁地描述您期望发生的事情。

## 截图
如果可以，请添加屏幕截图以帮助解释您的问题。

## 代码重现
选择一种方式即可

  ### Git 重现地址（推荐）
  您可以将可运行并且能复现问题的最简代码提交到 git 仓库（如 Github），然后提供给作者可访问的地址

  ### 关键代码
  尽可能留下关键代码片段，方便作者定位问题

  ``` javascript
 {
        path: '/',
        layout: HeaderAsideLayout,
        component:Index,
        redirect:"/index",
    },
  ```
![image](https://user-images.githubusercontent.com/20693737/61100027-1de3dc00-a497-11e9-81ff-9acdc02e339c.png)

这个pageRoute会是undefined

## 开发环境（请填写以下信息）
  - Node.js: [例如: v12.4.0]
  - Vue: [例如: v2.5.22]
  - Vue Router: [例如: V3.0.7]
  - **Vue Router Tab**: [例如: v0.2.0]

## 运行环境（请填写以下信息）
  - 设备: [例如: PC]
  - 操作系统: [例如: Windows 10]  
  - 浏览器和版本: [例如: Chrome 75.0.3770.100 x64]

## 附加内容
在此添加有关此问题的任何其他内容。

**Comment by bhuh12** [comment]
`layout: HeaderAsideLayout`

Vue Router 官方文档中没有 layout 配置项呢，请参考 [Router 构建选项 - routes](https://router.vuejs.org/zh/api/#router-%E6%9E%84%E5%BB%BA%E9%80%89%E9%A1%B9)

按我的理解， `HeaderAsideLayout` 是布局组件，这个布局里面应该包含 `<router-tab>` 组件，`Index` 组件是页签的页面，需要默认重定向到这里。如果理解没错的话，你的路由应当如下配置：

``` javascript
{
  path: '/',
  component: HeaderAsideLayout,
  redirect: '/index',
  children: [{
    path: '/index',
    component: Index,
    meta: {
      title: '首页页签标题'
    }
  }],
  // ... 其他页签页面的路由
}
```

具体请参考 Vue Router Tab 文档：[入门-路由配置](https://bhuh12.github.io/vue-router-tab/guide/essentials/#%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE)

**Comment by bhuh12** [comment]
请问问题是否解决呢？
