### ISSUE TITLE
嵌套子路由 点击为什么上方也会出现相关的tab按钮

### ISSUE THREAD

**Issue by zmhaodiao** [bhuh12/vue-router-tab#22]
![QQ截图20190716174430](https://user-images.githubusercontent.com/26317275/61284975-a1ccf980-a7f2-11e9-887f-6200253c447d.jpg)
![QQ截图20190716174456](https://user-images.githubusercontent.com/26317275/61284978-a2659000-a7f2-11e9-9a89-b125246ee6e1.jpg)
![QQ截图20190716175243](https://user-images.githubusercontent.com/26317275/61284982-a396bd00-a7f2-11e9-8d74-13246f8df231.jpg)

**Comment by bhuh12** [comment]
你当前使用的 Vue Router Tab 版本多少？0.2.0 是已经解决了这个问题的

**Comment by zmhaodiao** [comment]
> 你当前使用的 Vue Router Tab 版本多少？0.2.0 是已经解决了这个问题的

兄弟出一个更新文档啦... 这个问题折磨我很久了

**Comment by bhuh12** [comment]
[https://github.com/bhuh12/vue-router-tab/releases](https://github.com/bhuh12/vue-router-tab/releases)

从这两个地方可以看更新日志，更新后问题能解决吗？

![image](https://user-images.githubusercontent.com/9862292/61351624-c16d2c00-a89d-11e9-9650-d930a9234582.png)

![image](https://user-images.githubusercontent.com/9862292/61351637-ccc05780-a89d-11e9-9cd5-5dc3bba11e0d.png)

**Comment by zmhaodiao** [comment]
> 从这两个地方可以看更新日志，更新后问题能解决吗？

ok已解决  加油！
