### ISSUE TITLE
iframe 交互操作的时候,我无法判断iframe是什么时候加载完的，第一次初始化postMessage无法传值，并且无法给iframe标识来获取contentWindow

### ISSUE THREAD

**Issue by zmhaodiao** [bhuh12/vue-router-tab#23]
![QQ截图20190717155745](https://user-images.githubusercontent.com/26317275/61357852-a7d2e100-a8ab-11e9-8039-c9e766bd8c71.jpg)

**Comment by bhuh12** [comment]
已在 `feat-iframe-event` 分支上提交代码，你可以本地构建开发版体验一下，如果没问题的话近期会发布新版本。

请参考 [安装-构建开发版](https://bhuh12.github.io/vue-router-tab/guide/installation.html#%E6%9E%84%E5%BB%BA%E5%BC%80%E5%8F%91%E7%89%88)，切换至 `feat-iframe-event` 分支构建并体验

参考文档：[iframe 页签事件](https://github.com/bhuh12/vue-router-tab/blob/feat-iframe-event/docs/guide/essentials/iframe.md#iframe-%E9%A1%B5%E7%AD%BE%E4%BA%8B%E4%BB%B6)

![image](https://user-images.githubusercontent.com/9862292/61396732-f065bb00-a8fa-11e9-9ce7-91888dcabda1.png)

**Comment by bhuh12** [comment]
0.2.1版本已支持上述 iframe 页签事件
