### ISSUE TITLE
页签标题动态化处理

### ISSUE THREAD

**Issue by linusok** [bhuh12/vue-router-tab#25]
我抽象了一个页面级组件，需要多次重复打开在不同的页签里，但是目前页签的标题只能在路由的meta里配置，而vue-router相应的this.$router.push方法是无法修改meta信息的。
![image](https://user-images.githubusercontent.com/9760598/62668177-6a9ad400-b9bd-11e9-8b47-a25bb3e4bff4.png)
例如上图是我的路由，不同的页签会因为传入的formid不同而不同，但是页签的名称无法动态变化

希望考虑同一个组件在不同页签多次打开后针对页签属性的更新提供一个方案，可以在路由中约定额外的一个数据对象如：tab:{title:'',icon:''}，当存在此对象时优先使用，否则考虑meta中的信息以达到兼容以前的做法。

## 描述您考虑过的替代方案
mount时，访问原生dom对象进行更新，不过这个完全不是数据驱动的思路，最后放弃了。

**Comment by bhuh12** [comment]
请参考：[动态更新页签](https://bhuh12.github.io/vue-router-tab/guide/advanced/dynamic-tab-info.html)

可以动态更新页签数据

**Comment by linusok** [comment]
> 请参考：[动态更新页签](https://bhuh12.github.io/vue-router-tab/guide/advanced/dynamic-tab-info.html)
> 
> 可以动态更新页签数据

不好意思，没好好看文档。晕菜。
