### ISSUE TITLE
严重的内存泄漏问题

### ISSUE THREAD

**Issue by DroidC** [bhuh12/vue-router-tab#26]
## Bug 描述
严重的内存泄漏问题，被销毁的组件并不能回收内存。

## 问题重现
重现行为的步骤：
1. 打开demo页
2. 打开chrome devtool， 打开Performance Monitor
3. 不停点击刷新按钮，然后打开多个页签再关闭

## 预期行为
内存和DOM持续增加，不能被GC回收，我在实际项目中 ，长时间使用后，关闭所有页签，产生数十万dom和超过1g的js heap也没有被gc回收，确定为内存泄漏问题

## 截图
![image](https://user-images.githubusercontent.com/19756831/62747274-4e169e80-ba86-11e9-9c3b-203000deb917.png)

## 开发环境（请填写以下信息）
  - Node.js: v10.13.0
  - Vue: v2.6.10
  - Vue Router: V3.0.1
  - **Vue Router Tab**: v0.2.0

## 运行环境（请填写以下信息）
  - 设备: PC
  - 操作系统: Windows 10
  - 浏览器和版本: Chrome最新正式版

**Comment by bhuh12** [comment]
特意了解了一下 Chrome 官方的开发工具文档，按以下步骤记录快照

1. 根据 “问题重现” 中的步骤：
   1. 打开官方 Demo 页面
   2. 刷新 10 次 “页面1”
   3. 打开 “页面2” 至  “页面10” 的 9 个页签
   4. 右键 “页面1” 点击 “关闭其他”，关掉其他页签
2. 打开 Chrome 开发者工具的 **Memory** 页签，点击 **Take Heap Snapshot** 生成 **HEAP SNAPSHOTS** 快照，此时为 Snapshot 1
3. 打开 “页面2” ，重新生成快照 Snapshot 2
4. 分别在 Snapshot 1 和 Snapshot 2 的 **Class filter** 文本框中键入 **Detached**，搜索已分离的 DOM 树。


### 首次进入页面

Performance monitor 记录值：

| 属性 | 值 |
|--- |--- |
| JS heap size | 9.7 MB |
| DOM Nodes | 235 |


![image](https://user-images.githubusercontent.com/9862292/62820729-fae24000-bb9a-11e9-937d-57e4dffe1f42.png)


### Snapshot 1 Detached 过滤结果 (单个页签)

Performance monitor 记录值：

| 属性 | 值 |
|--- |--- |
| JS heap size | 10.2 MB |
| DOM Nodes | 216 |


如下图所示，过滤结果中未找到已分离的 Dom，DOM Nodes数量相对首次进入也没太大改变

![image](https://user-images.githubusercontent.com/9862292/62820652-05e8a080-bb9a-11e9-89e4-eb769aa8dcb8.png)


### Snapshot 2 Detached 过滤结果 (两个页签)


Performance monitor 记录值：

| 属性 | 值 |
|--- |--- |
| JS heap size | 10.2 MB |
| DOM Nodes | 331 |


如下图所示，过滤结果中可找到已分离的 Dom，DOM Nodes数量相对单个页签增加了 115。

分析原因，“页面1” 的 DOM 节点因为页签隐藏，并未出现在 document 内，所以情况是也是符合预期的

![image](https://user-images.githubusercontent.com/9862292/62820705-7e4f6180-bb9a-11e9-8fb1-ebc35517525f.png)

---

## 分析：

在点击 **Take Heap Snapshot** 生成快照之前，Performance monitor 中的 DOM Nodes 值确实会出现随着操作越来越多的情况，生成快照后，DOM Nodes 就恢复正常了。

按个人理解，开发工具生成快照前会执行强制回收内存，如果回收后还发现有不在页面内的 Dom Nodes，说明这些节点是被其他变量引用的。如果真的出现内存泄漏，在这里应该也是可以看到的。

因为浏览器的内存回收也是会占用系统资源的，所以浏览器会按一定的规则，在需要的时候才开启。js 好像也没办法直接控制强制回收。

我们这里看到 Performance monitor 数据越来越大，可能到只是还没触发浏览器自动回收内存的阈值

---

多页签页面，相对于普通的单页面，由于需要同时保存多个页面状态，肯定是会占用更多的资源。后续 Router Tab 可能会添加配置来限制页签数量，以减少类似的性能问题。

建议你也参考 Chrome 开发工具官方的文档来分析一下，定位问题的根因。

> 参考 [ Tools for Web Developers - 解决内存问题 - 使用堆快照发现已分离_dom_树的内存泄漏](https://developers.google.com/web/tools/chrome-devtools/memory-problems/#%E4%BD%BF%E7%94%A8%E5%A0%86%E5%BF%AB%E7%85%A7%E5%8F%91%E7%8E%B0%E5%B7%B2%E5%88%86%E7%A6%BB_dom_%E6%A0%91%E7%9A%84%E5%86%85%E5%AD%98%E6%B3%84%E6%BC%8F)

以上观点，或有谬误，也欢迎讨论指正

**Comment by DroidC** [comment]
> 特意了解了一下 Chrome 官方的开发工具文档，按以下步骤记录快照
> 
> 1. 根据 “问题重现” 中的步骤：
>    
>    1. 打开官方 Demo 页面
>    2. 刷新 10 次 “页面1”
>    3. 打开 “页面2” 至  “页面10” 的 9 个页签
>    4. 右键 “页面1” 点击 “关闭其他”，关掉其他页签
> 2. 打开 Chrome 开发者工具的 **Memory** 页签，点击 **Take Heap Snapshot** 生成 **HEAP SNAPSHOTS** 快照，此时为 Snapshot 1
> 3. 打开 “页面2” ，重新生成快照 Snapshot 2
> 4. 分别在 Snapshot 1 和 Snapshot 2 的 **Class filter** 文本框中键入 **Detached**，搜索已分离的 DOM 树。
> 
> ### 首次进入页面
> Performance monitor 记录值：
> 
> 属性	值
> JS heap size	9.7 MB
> DOM Nodes	235
> ![image](https://user-images.githubusercontent.com/9862292/62820729-fae24000-bb9a-11e9-937d-57e4dffe1f42.png)
> 
> ### 完成“问题重现” 中的步骤
> Performance monitor 记录值：
> 
> 属性	值
> JS heap size	13.9 MB
> DOM Nodes	1234
> 发现有大量 DOM Nodes 改动，JS heap size 也增加了不少
> 
> ![image](https://user-images.githubusercontent.com/9862292/62822786-b4044280-bbba-11e9-9dc4-d5e2e81dada8.png)
> 
> ### Snapshot 1 Detached 过滤结果 (单个页签)
> Performance monitor 记录值：
> 
> 属性	值
> JS heap size	10.2 MB
> DOM Nodes	216
> 如下图所示，过滤结果中未找到已分离的 Dom，DOM Nodes数量相对首次进入也没太大改变
> 
> ![image](https://user-images.githubusercontent.com/9862292/62820652-05e8a080-bb9a-11e9-89e4-eb769aa8dcb8.png)
> 
> ### Snapshot 2 Detached 过滤结果 (两个页签)
> Performance monitor 记录值：
> 
> 属性	值
> JS heap size	10.2 MB
> DOM Nodes	331
> 如下图所示，过滤结果中可找到已分离的 Dom，DOM Nodes数量相对单个页签增加了 115。
> 
> 分析原因，“页面1” 的 DOM 节点因为页签隐藏，并未出现在 document 内，所以情况是也是符合预期的
> 
> ![image](https://user-images.githubusercontent.com/9862292/62820705-7e4f6180-bb9a-11e9-8fb1-ebc35517525f.png)
> 
> ## 分析：
> 在点击 **Take Heap Snapshot** 生成快照之前，Performance monitor 中的 DOM Nodes 值确实会出现随着操作越来越多的情况，生成快照后，DOM Nodes 就恢复正常了。
> 
> 按个人理解，开发工具生成快照前会执行强制回收内存，如果回收后还发现有不在页面内的 Dom Nodes，说明这些节点是被其他变量引用的。如果真的出现内存泄漏，在这里应该也是可以看到的。
> 
> ![image](https://user-images.githubusercontent.com/9862292/62822718-d184dc80-bbb9-11e9-9916-47620d55e249.png)
> 
> ### Chrome 强制回收按钮
> ![image](https://user-images.githubusercontent.com/9862292/62821543-1b18fb80-bba9-11e9-9ee0-acf6a150b90c.png)
> 
> 因为浏览器的内存回收也是会占用系统资源的，所以浏览器会按一定的规则，在需要的时候才开启。js 好像也没办法直接控制强制回收。
> 
> 我们这里看到 Performance monitor 数据越来越大，可能只是还没触发浏览器自动回收内存的阈值。如果从快照里面发现大量异常的已分离 DOM 节点，才能说明是有 DOM 内存泄漏。
> 
> 多页签页面，相对于普通的单页面，由于需要同时保存多个页面状态，肯定是会占用更多的资源。后续 Router Tab 可能会添加配置来限制页签数量，以减少类似的性能问题。
> 
> 建议你也参考 Chrome 开发工具官方的文档来分析一下，定位问题的根因。
> 
> > 参考 [ Tools for Web Developers - 解决内存问题 - 使用堆快照发现已分离_dom_树的内存泄漏](https://developers.google.com/web/tools/chrome-devtools/memory-problems/#%E4%BD%BF%E7%94%A8%E5%A0%86%E5%BF%AB%E7%85%A7%E5%8F%91%E7%8E%B0%E5%B7%B2%E5%88%86%E7%A6%BB_dom_%E6%A0%91%E7%9A%84%E5%86%85%E5%AD%98%E6%B3%84%E6%BC%8F)
> 
> 以上观点，或有谬误，也欢迎讨论指正

感谢耐心的分析和回复，我会进行后续测试

**Comment by bhuh12** [comment]
RoutertTab v0.2.1 版本，在组件销毁后添加了缓存清理动作，可以更新看看是否有所改善
