### ISSUE TITLE
Readme and documentation in english?

### ISSUE THREAD

**Issue by trondulseth** [bhuh12/vue-router-tab#28]
Looks like a cool/good project that would be usefull

Any plans of making the readme and documentation in english?

**Comment by luhaopeng** [comment]
I could help translate if needed :)

---

如果有计划的话，我可以帮忙翻译。

**Comment by bhuh12** [comment]
> I could help translate if needed :)
> 
> 如果有计划的话，我可以帮忙翻译。

非常感谢，我近期整理一下项目 Doc 和 Demo 的国际化

**Comment by bhuh12** [comment]
> > I could help translate if needed :)
> > 如果有计划的话，我可以帮忙翻译。
> 
> 非常感谢，我近期整理一下项目 Doc 和 Demo 的国际化

已邀请协作。

## 协作流程
1. 本地克隆项目后切换 `doc-locales` 分支（翻译完成后再合并 dev 分支并自动构建）。
2. 安装 npm 依赖后，执行 `npm run docs:dev` 启动文档本地开发服务
3. 编辑需要翻译的内容，使用 git 暂存更改后，执行命令 `npm run commit` 提交修改：
    1. Select the type of change that you're committing: **docs**
    2. What is the scope of this change: **locales**
    3. Write a short, imperative tense description of the change: **你的提交消息**
  最终提交的消息示例：docs(locales): 翻译插件 api 相关英文文档

## 需要翻译的内容
| 文件或目录 | 说明 |
| ---- | ---- |
| README.{locale}.md | 项目说明，如：README.en.md |
| docs/.vuepress/locales/{locale}.js | vuepress 项目多语言配置，如：docs/.vuepress/locales/en.js 是英文项目配置 |
| docs/{locale}/**.md | 多语言文档，如：docs/en 是英文文档目录 |


### 再次感谢协助翻译！
