### ISSUE TITLE
怎么关闭或刷新除指定页面外所有页面，这种交互是很多的。

### ISSUE THREAD

**Issue by zmhaodiao** [bhuh12/vue-router-tab#29]
api 只有关闭指定页面，一旦打开很多tab其中还包含iframe的table,不可能去一个一个指定的关闭。table页签的右键 关闭其他 的功能怎么用代码触发？ 
刷新操作 应该也有一个触发 刷新其他的功能。

**Comment by bhuh12** [comment]
目前提供了[重置页签](https://bhuh12.github.io/vue-router-tab/guide/essentials/operate.html#%E9%87%8D%E7%BD%AE%E9%A1%B5%E7%AD%BE)的方法来重置页签到初始状态
