### ISSUE TITLE
tab 标签不支持打开一个普通网址吧？？

### ISSUE THREAD

**Issue by qmdx** [bhuh12/vue-router-tab#3]
例如打开 baidu

**Comment by bhuh12** [comment]
你说的是单纯的加一个浏览器新窗口的链接，还是iframe方式嵌入呢？
两者都可以作为新需求纳入。

**Comment by bhuh12** [comment]
你说的是单纯的加一个浏览器新窗口的链接，还是iframe方式嵌入呢？
两者都可以作为新需求纳入。

**Comment by bhuh12** [comment]
嵌入iframe的页签，你可以通过这样的方式实现:
RouterTab组件的子路由里面添加路由 'frame/:title/:url'，然后新建Frame.vue组件，里面根据链接的参数template输出iframe节点，js里动态修改页签标题。

然后根据这个路由就能直接打开iframe页签了

**Comment by bhuh12** [comment]
我很久之前在Chrome下遇到过一个问题，是iframe节点位置发生改变后，iframe内容会重新加载。刚才搜索了一下，也有其他人提出过，但是暂时没看到好的解决方案。

https://www.vue-js.com/topic/5badd3b042cb479054848e13
