### ISSUE TITLE
页面缓存还是无法清理，tab关闭后会有Detached HTML元素

### ISSUE THREAD

**Issue by lvdongbo** [bhuh12/vue-router-tab#31]
## Bug 描述
打开新的tab，再把它关闭后，通过谷歌的工具发现存在Detached HTML元素，该tab对应的页面缓存没有被清理。

## 问题重现
重现行为的步骤：
1. 打开新tab
2. 关于打开的tab
3. F12打开谷歌的开发者工具
4. 点击【Memory】->【Take snapshot】
5. 在Shanpshot里面查找Detached，可以看到有很多未释放的DOM元素

## 预期行为
TAB关闭后，该tab内组件占用的内存能够完全释放

## 截图
![image](https://user-images.githubusercontent.com/3377661/67749923-1b6ab980-fa69-11e9-8b74-1e98320fbad9.png)

## 代码重现

Git 重现地址如下：
https://github.com/lvdongbo/vue-tab-test.git

## 开发环境（请填写以下信息）
  - Node.js: v10.16.0
  - Vue: v2.6.10
  - Vue Router: V3.1.3
  - **Vue Router Tab**: v0.2.7

## 运行环境（请填写以下信息）
  - 设备: PC
  - 操作系统: Windows 10
  - 浏览器和版本: Chrome  77.0.3865.120 x64

**Comment by bhuh12** [comment]
感谢反馈。确实会有些操作会持续增加 Detached HTML

**Comment by bhuh12** [comment]
在 `1.0.0` 版本，RouterTab 的核心组件 RouterAlive 已经使用 `<router-view>` + `<keep-alive>` 重构，组件缓存基于原生 KeepAlive 控制。在内存释放方面，应该比之前的方案更好。

相较之前的版本，新版本拥有更好的缓存控制能力，也带来了一些新的功能，欢迎使用。

[更新日志](https://bhuh12.github.io/vue-router-tab/zh/guide/changelog.html)
