### ISSUE TITLE
建议能够支持3级及以上的路由，并且能够缓存起来，以便于tab切换。

### ISSUE THREAD

**Issue by zxhbloomer** [bhuh12/vue-router-tab#32]
建议能够支持3级及以上的路由，看了一下demo，嵌套三级目录的并没有在tab上显示出来，而是在页面中作为一个单独的router-view中显示出来。

**Comment by bhuh12** [comment]
RouterTab 控件是有意设计成这样的，只有包含 RouterTab 组件的路由的**直接子路由**才参与生成页签页面，再嵌套的下级路由跟 Vue Router 中一样展现。

试想一下，一个页签页面内部还有**子页签**控制页面展示，并且子页签也需要响应路由，这种场景是必须嵌套路由支持的

**Comment by zxhbloomer** [comment]
嗯，大大说的很对，嵌套路由确实如此。
不过，大大考虑一下实际业务场景，可能就是需要3级目录。
感觉，3级目录+keepalive，无解啊

**Comment by bhuh12** [comment]
不清楚你的具体场景，不过为什么不可以将三级路由提到二级呢，直接放到包含 RouterTab 组件的子路由里面

**Comment by zxhbloomer** [comment]
如下图
![image](https://user-images.githubusercontent.com/12026777/69615658-392f3c80-1070-11ea-9946-04b6895850d4.png)

**Comment by bhuh12** [comment]
路由的层级不需要跟菜单层级保持一致啊

**Comment by zxhbloomer** [comment]
嗯，确实可以这么办
