### ISSUE TITLE
文档/教程/方案 中第3点表述有误

### ISSUE THREAD

**Issue by luhaopeng** [bhuh12/vue-router-tab#34]
我在翻译文档的过程中，发现以下一点的表述有误：

> https://bhuh12.github.io/vue-router-tab/guide/program.html
> 3. 由于缓存，Webpack 热加载后的页面不刷新：
>
> 在路由页面组件全局混入的 activated 钩子里，记录 vm.$vnode.componentOptions.Ctor.cid。如果与上一次的值不一致，则销毁页面，组件重新渲染

实际上，在[ab4bfd4](https://github.com/bhuh12/vue-router-tab/commit/ab4bfd4838b770b7af96e345e7da89bcc217adb1)这次commit中就已经把上述的这部分代码，从`routerPage.js`的activated hook中，移到了`RouterAlive.js`的render函数中了。

我会按照实际代码中的情况翻译 :)

**Comment by bhuh12** [comment]
好的，多谢了。我中文文档到时候也更新下。

**Comment by bhuh12** [comment]
##已更新文档：[docs: 更新方案3：Webpack 热加载后的页面不刷新](https://github.com/bhuh12/vue-router-tab/commit/deda0305b052ac42bee7d237948a6a570f49208f)
