### ISSUE TITLE
Error in getter for watcher "restoreKey"

### ISSUE THREAD

**Issue by chenzhe555** [bhuh12/vue-router-tab#35]
## Bug 描述
参照 https://bhuh12.github.io/vue-router-tab/guide/essentials/#%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE 安装和入门完成后，报错标题所示例错误：

Error in getter for watcher "restoreKey": "TypeError: Cannot read property 'path' of undefined"

vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'path' of undefined
    at VueComponent.getBasePath (vue-router-tab.umd.min.js?f57d:1)
    at VueComponent.restoreKey (vue-router-tab.umd.min.js?f57d:1)

## 截图
![截屏2020-02-16上午10 50 09](https://user-images.githubusercontent.com/6481942/74598301-327df780-50aa-11ea-8d2e-388fc41cb641.jpg)

  ### 关键代码
  "vue": "^2.6.11",
   "vue-router": "^3.1.3",

 

## 开发环境（请填写以下信息）
  - Node.js: [例如: v12.4.0]
  - Vue: [例如: v2.5.22]
  - Vue Router: [例如: V3.0.1]
  - **Vue Router Tab**: [例如: v0.2.0]
node 12.11.0
"vue": "^2.6.11",
"vue-router": "^3.1.3",
 "vue-router-tab": "^1.0.0-alpha.1",

## 运行环境（请填写以下信息）
 Chrome

**Comment by bhuh12** [comment]
包含 RouterTab 组件的路由，请添加 redirect 跳转直接子级路由。页签是由直接子级路由提供的
