### ISSUE TITLE
demo 中的this.$routerTab is undefined 

### ISSUE THREAD

**Issue by chenyuhu** [bhuh12/vue-router-tab#36]

**Comment by bhuh12** [comment]
`$routerTab`
漏了 r

**Comment by chenyuhu** [comment]
![WX20200222-185639@2x.png](https://i.loli.net/2020/02/22/qn1xK4OdMvWR5Jf.png)
![WX20200222-185907@2x.png](https://i.loli.net/2020/02/22/Yji4dx2NW86QPAo.png)

不好意思，标题上打错了，实际上没有少

**Comment by bhuh12** [comment]
RouterTab 组件在 created 钩子时会注入到 Vue 原型，因此，你只能在这之后访问 this.$routerTab

**Comment by chenyuhu** [comment]
貌似还是不行

**Comment by bhuh12** [comment]
你是在什么场景下需要访问 RouterTab 呢？如果 RouterTab 都没创建组件，肯定是无法访问的，即使访问也没意义啊

**Comment by chenyuhu** [comment]
点击事件的时候触发，需要用到this.$routerTab.open()

**Comment by chenyuhu** [comment]
vue-cli 2.x 的项目不可以使用的吗？

**Comment by bhuh12** [comment]
可以用啊，页签组件展示正常吗？
你贴一下事件相关页面组件代码

**Comment by chenyuhu** [comment]
页签组件展示正常
#### 入口文件
``` js
....
import RouterTab from 'vue-router-tab'
Vue.use(RouterTab)
.....
```

#### 路由文件
```js
import Vue from 'vue'
import Router from 'vue-router'
import { RouterTabRoutes } from 'vue-router-tab'
Vue.use(Router)
export default new Router({
  routes: [
    {
      path: '/',
      redirect: '/home'
    },
    {
      path: '/home',
      name: '主页',
      component: () => import('../../components/workWin/Home/Home'),
      meta: {
        title: '主页'
      }
    },
    {
      path: '/childMod',
      name: '子功能模块',
      component: () => import('../../components/workWin/Home/SubModuleFun')
    },
    {
      path: '/work',
      name: '工作模块',
      meta: {
        title: '工作模块'
      },
      component: () => import('../../components/workWin/workHome'),
      children: [
        ...RouterTabRoutes,
        ...dailyWork
      ]
    }
  ]
})
```


#### 使用文件
```vue
<!--  -->
<template>
  <div>
    <router-tab></router-tab>
  </div>
</template>

<script>
export default {
  data() {
    return {}
  },
  props: {},
  methods: {},
  created() {},
  components: {},
  watch: {},
  computed: {},
  mounted() {
    console.log(this.$routerTab)
  }
}
</script>

<style scoped lang="scss"></style>
```

**Comment by bhuh12** [comment]
你 **使用文件** 的代码是 `../../components/workWin/workHome` 吗？

mounted 里面加 `debugger` 调试看能否进入

实在不行你将能重现问题的最简代码放 github 我看看

**Comment by bhuh12** [comment]
而且通常是不建议直接使用 this.$routerTab.open() 打开页签的，这个方法会刷新之前存在的已经打开过的地址

推荐是使用 `router-link` 和 `$router.push`

![image](https://user-images.githubusercontent.com/9862292/75128674-3b04ac80-5700-11ea-9b7e-f1edbbfdfab9.png)

**Comment by chenyuhu** [comment]
![WX20200224-142825@2x.png](https://i.loli.net/2020/02/24/DF8cWXpmohs1MVC.png)
但是如果我要使用this.$routerTab 的方法还是不能使用的啊

**Comment by bhuh12** [comment]
将能重现问题的最简代码(剥离不需要的代码)放 github 我看看

**Comment by chenyuhu** [comment]
hi man 
demo 的地址在这儿https://github.com/chenyuhu/electron-tab.git  辛苦试一下吧

**Comment by bhuh12** [comment]
新的 `1.0.0-alpha.2` 版本应该能解决这个问题，你更新下看看

**Comment by chenyuhu** [comment]
谢谢

**Comment by chenyuhu** [comment]
非常感谢，问题解决了！
能加一下你的wx吗？ 我的是HQ580231CF 谢谢
