### ISSUE TITLE
没有默认路由时会报错

### ISSUE THREAD

**Issue by wtjperi2003** [bhuh12/vue-router-tab#39]
`vue-router-tab.umd.min.js?f57d:1 [Vue Router Tab] 未能匹配到路由信息
y @ vue-router-tab.umd.min.js?f57d:1
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in getter for watcher "restoreKey": "TypeError: Cannot read property 'path' of undefined"

found in

---> <RouterTab>
       <QPageContainer>
         <QLayout>
           <MainLayout> at src/layouts/MainLayout.vue
             <App> at src/App.vue
               <Root>`

**Comment by bhuh12** [comment]
页签组件必须要有可访问的路由才能生成页签
页签组件所在路由节点需要重定向到子路由，或者子路由配置跟父级路由 path 一样。

**Comment by bhuh12** [comment]
需要注意的地方我标红了，你可以检查一下。
如果还是无法解决，可以将能复现问题的最简代码放 github 上，我试试看

![1](https://user-images.githubusercontent.com/9862292/78338078-b3df0a00-75c4-11ea-8bf9-21adc8566ca4.png)
![2](https://user-images.githubusercontent.com/9862292/78338093-b8a3be00-75c4-11ea-92b1-f96d5d86e565.png)

**Comment by wtjperi2003** [comment]
使用"默认路由与父路由路径一致"可以解决报错的问题...

**Comment by bhuh12** [comment]
入门文档已添加默认路由配置相关说明，提醒后来者避免出错

https://bhuh12.github.io/vue-router-tab/guide/essentials/#%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE

![image](https://user-images.githubusercontent.com/9862292/78765917-38fa6280-79bb-11ea-8194-12994020c80f.png)
