### ISSUE TITLE
 this.matchRoutes(...).baseRoute is undefined

### ISSUE THREAD

**Issue by szwlxj** [bhuh12/vue-router-tab#40]
要看教程配置的，但一直出这个错误，找不出原因在哪，帮帮我吧，浪费了好几个小时了

 this.matchRoutes(...).baseRoute is undefined

**Comment by bhuh12** [comment]
是不是页签组件所在路由节点没有默认重定向到子路由？

**Comment by szwlxj** [comment]
谢谢你，找到问题所在了，确实是少写了一个地方：redirect

**Comment by bhuh12** [comment]
入门文档已添加默认路由配置相关说明，提醒后来者避免出错

https://bhuh12.github.io/vue-router-tab/guide/essentials/#%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE

![image](https://user-images.githubusercontent.com/9862292/78765917-38fa6280-79bb-11ea-8194-12994020c80f.png)
