### ISSUE TITLE
能添加一个tab被点击切换的事件吗

### ISSUE THREAD

**Issue by wtjperi2003** [bhuh12/vue-router-tab#41]
如果要实现点击切换tab后同时切换对应左侧菜单的高亮,这时候要用到啊

**Comment by bhuh12** [comment]
RouterTab 是基于 Vue Router 的，因此没有额外提供 tab 切换事件

菜单链接如果用 `router-link` 的话，可以用 `active-class` 和 `exact-active-class` 来控制激活的样式

如果用的其他的，可以用方法来判断是否激活，判断菜单地址和当前路径 `$route.fullPath` 、 `$route.path` 是否匹配

菜单组件内你可以 watch `$route` 改动来判断自动展开对应的父节点

参考链接：https://router.vuejs.org/zh/api/#active-class
