### ISSUE TITLE
请问关闭一个页签，为什么页面还停留在这个页签的页面上，没有跳转。

### ISSUE THREAD

**Issue by superDino** [bhuh12/vue-router-tab#42]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Development Environment (please complete the following information):**
 - Node.js: [e.g. v12.4.0]
 - Vue: [e.g. v2.5.22]
 - Vue Router [e.g. v3.0.1]
 - **Vue Router Tab** [e.g. v0.2.0]

**Operating Environment (please complete the following information):**
 - Device: [e.g. Desktop]
 - OS: [e.g. Windows 10]
 - Browser [e.g. stock browser, Chrome]
 - Version [e.g. 75]

**Additional context**

**Comment by bhuh12** [comment]
是手动点击页签上的按钮关闭，还是代码控制的关闭的？
控制台有无错误出现？

**Comment by superDino** [comment]
手动点击页签上的按钮关闭，控制台无错误出现，按照流程不是应该关闭页签后跳到上一次打开的页面吗？还是我有些配置没有做。

**Comment by superDino** [comment]
> 是手动点击页签上的按钮关闭，还是代码控制的关闭的？
> 控制台有无错误出现？

手动点击页签上的按钮关闭，控制台无错误出现，按照流程不是应该关闭页签后跳到上一次打开的页面吗？还是我有些配置没有做。

**Comment by bhuh12** [comment]
能否将重现问题的最小代码提交到 github，我看看

**Comment by superDino** [comment]
> 能否将重现问题的最小代码提交到 github，我看看
抱歉这么久回复你，是这样的情况，和代码应该没有太大关系。就页面上同时有很多个页签，我选择一个页签，然后点页签的叉叉关闭他，但这个时候路由还是这个页签的路由，关掉这个页签不是应该跳转到路由历史上最近的路由上面吗？页面内容也随之改变。

**Comment by superDino** [comment]
> 能否将重现问题的最小代码提交到 github，我看看

抱歉这么久回复你，是这样的情况，和代码应该没有太大关系。就页面上同时有很多个页签，我选择一个页签，然后点页签的叉叉关闭他，但这个时候路由还是这个页签的路由，关掉这个页签不是应该跳转到路由历史上最近的路由上面吗？页面内容也随之改变。

**Comment by bhuh12** [comment]
没办法重现不方便定位问题呢

**Comment by bhuh12** [comment]
请问问题是否解决呢
