### ISSUE TITLE
maybe tab should not use the route

### ISSUE THREAD

**Issue by tristan-tsl** [bhuh12/vue-router-tab#43]
## 您的需求是否与问题有关？
yes

## 描述你想要的解决方案
in fact, i don't need the route and i can't effect the route, can you provide a useful without router? thank you

## 描述您考虑过的替代方案
i try to use iview Tabs, but its remove function always have probleam, but it was very clear

**Comment by bhuh12** [comment]
Router Tab 是基于 Vue Router 的路由管理实现的，会响应当前路由地址来打开或者切换页签。这个是我们的核心功能，因此并没有计划会提供不依赖 router 的独立版本。
 
在我看来，如果不依赖 router，iview Tabs 和 Element Tabs 都会是很棒的方案。

**Comment by tristan-tsl** [comment]
Yes, thank you, in a few ago i already temp deal with iview tabs remove function' bug
