### ISSUE TITLE
English documentation as primary

### ISSUE THREAD

**Issue by Scrum** [bhuh12/vue-router-tab#46]
Is it possible to set the English documentation as the main one?

**Comment by bhuh12** [comment]
You can click this link to switch languages.

Document translation is not yet complete, you can access these pages through Google translation

![image](https://user-images.githubusercontent.com/9862292/79745904-b1f2a600-833b-11ea-8099-07661f5f265e.png)

**Comment by Scrum** [comment]
Thank you, I saw that it is possible to switch to another language, I was interested in can you make the English version of the documentation primary?

**Comment by bhuh12** [comment]
I'm sorry about that, my English is terrible, I need someone to help translate these documents first.

**Comment by Scrum** [comment]
The current documentation on the github in the English version is pretty good.
