### ISSUE TITLE
Tab数量过多的情况下不支持左右切换

### ISSUE THREAD

**Issue by Wetoria** [bhuh12/vue-router-tab#5]
![image](https://user-images.githubusercontent.com/16909518/55669398-617fe600-58a9-11e9-8e9b-df035bfe07a8.png)

**Comment by bhuh12** [comment]
请问问题能在官方demo重现吗？
如能重现，重现的浏览器和版本麻烦提供一下。
demo如果不能重现的话，你可以把出现问题的代码新建github仓库提交上去。我看看。
官方demo:https://bhuh12.github.io/vue-router-tab/demo/
