### ISSUE TITLE
Auto refresh when clicking on a tab

### ISSUE THREAD

**Issue by dalholm** [bhuh12/vue-router-tab#55]
a general setting or a meta setting where you could fore reload on click

**Comment by bhuh12** [comment]
This feature is already supported in `v1.0.0` 

Docs: [https://bhuh12.github.io/vue-router-tab/guide/essentials/cache.html#keep-alive](https://bhuh12.github.io/vue-router-tab/guide/essentials/cache.html#keep-alive)

Note that this version has some [BREAKING CHANGES](https://bhuh12.github.io/vue-router-tab/guide/changelog.html)
