### ISSUE TITLE
可以考虑增加页签数量过多时的左右滑动控制吗？

### ISSUE THREAD

**Issue by CFish-AI** [bhuh12/vue-router-tab#57]
当打开了很多页面后，页签处显示不下每个页签，可以考虑一下增加左移、右移的功能按钮吗？
另外在右边，是否可以考虑增加几个自定义的按钮，例如常用到的“全屏”、“退出”等，具体执行的方法自定义。

**Comment by bhuh12** [comment]
目前时支持左右移动的，后续会加上鼠标滚轮滑动
![image](https://user-images.githubusercontent.com/9862292/82171494-13397500-98fa-11ea-9323-ead446e835b1.png)

后续会通过 slot 插槽方式允许页签前后添加自定义内容

**Comment by bhuh12** [comment]
`1.0.0-alpha.5` 已支持**鼠标滚轮滑动**和页签**前后插槽**

Docs: https://bhuh12.github.io/vue-router-tab/zh/guide/advanced/slot.html
Demo: https://bhuh12.github.io/vue-router-tab/demo/#/slot/

**Comment by CFish-AI** [comment]
忙于项目忘记来回复了，感谢大佬，完美解决了我的困惑
