### ISSUE TITLE
問題請教有關router

### ISSUE THREAD

**Issue by iam009tw** [bhuh12/vue-router-tab#6]
1. 請問i18n有示範的案例可以參考嗎?
2. 另外我有嘗試把vue-i18n-sandbox 範例的檔案整合, 但是code使用get取得目錄底下json檔案，但是無法讀取到檔案，不知道如何設定router

fetch(`../lang/${locale}.json` , {
        method: 'get',
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json'
        }
      })

**Comment by bhuh12** [comment]
如果是基于webpack的项目直接import语言包就好了，也没必要json文件，直接js文件export default {...}。
fetch获取的json地址在打包后的目录应该是不存在的，所以无法读取。

另外，RouterTab 暂时还没支持路由页签信息的国际化，这两天如果有时间我会加上。

**Comment by iam009tw** [comment]
辛苦了，感謝回覆

**Comment by bhuh12** [comment]
刚发布的 v0.1.9 已经支持了 router 页签信息的国际化配置了

参考文档: [https://bhuh12.github.io/vue-router-tab/guide/essentials/i18n.html](https://bhuh12.github.io/vue-router-tab/guide/essentials/i18n.html)

Demo: [https://bhuh12.github.io/vue-router-tab/demo/#/i18n/lang](https://bhuh12.github.io/vue-router-tab/demo/#/i18n/lang)
