### ISSUE TITLE
运行代码没有出现小标签

### ISSUE THREAD

**Issue by callh** [bhuh12/vue-router-tab#61]
## Bug 描述
参照了文档写的，运行代码没有出现小标签，请大佬有空瞧瞧。

## 截图
![image](https://user-images.githubusercontent.com/39425860/86919163-62619080-c15a-11ea-9b05-7600f65a0c4f.png)

![image](https://user-images.githubusercontent.com/39425860/86919402-c08e7380-c15a-11ea-8901-38fa8adb7489.png)

![image](https://user-images.githubusercontent.com/39425860/86919494-e6b41380-c15a-11ea-92a9-a882d42942d7.png)

![image](https://user-images.githubusercontent.com/39425860/86919544-fcc1d400-c15a-11ea-8a47-31f40bd8923b.png)

**Comment by callh** [comment]
我试着退到1.0.1版本也是一样的

**Comment by bhuh12** [comment]
可以将重现问题的最简代码发布github我运行看看吗？从截图这里没看出问题呢

**Comment by callh** [comment]
附件为精简版代码，能复现问题，请过目，非常感谢百忙之中的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"碧海幽虹"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月9日(星期四) 中午11:28
收件人:&nbsp;"bhuh12/vue-router-tab"<vue-router-tab@noreply.github.com&gt;;
抄送:&nbsp;"官振"<guanzhen.li@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bhuh12/vue-router-tab] 运行代码没有出现小标签 (#61)





 
可以将重现问题的最简代码发布github我运行看看吗？从截图这里没看出问题呢
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

src.zip (79.69M, 2020年08月08日 11:36 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=0c3836329d9b319ff911b33f1264074b54590001570650551d5e570450490155510e1b0a01000c49530b575104070c05035e0e5634633517425b18485d143559&t=exs_ftn_download&code=08624d5d

**Comment by callh** [comment]
此外，我的nodejs版本是&nbsp;v12.16.1


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"碧海幽虹"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月9日(星期四) 中午11:28
收件人:&nbsp;"bhuh12/vue-router-tab"<vue-router-tab@noreply.github.com&gt;;
抄送:&nbsp;"官振"<guanzhen.li@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bhuh12/vue-router-tab] 运行代码没有出现小标签 (#61)





 
可以将重现问题的最简代码发布github我运行看看吗？从截图这里没看出问题呢

**Comment by bhuh12** [comment]
找到问题原因了，低版本的 vue 模板编译 slot插槽方式不一样。
我这里先看看有什么方案避免这类问题，你先将 `package.json` 的 `vue-template-compiler` 依赖版本改成这个试试：

``` json
{
"devDependencies": {
    "vue-template-compiler": "^2.6.10"
  }
}
```

**Comment by callh** [comment]
OK，解决了，看来是我这套环境有点儿老了，实在太感谢了！
