### ISSUE TITLE
router.push报错

### ISSUE THREAD

**Issue by roc0zhang** [bhuh12/vue-router-tab#62]
在嵌套<route-tab />的页面调用this.$router.push({path:'xxx'})报错
vue-router.esm.js?8c4f:2181 TypeError: Cannot read property 'path' of undefined
    at t.get (vue-router-tab.umd.min.js?f57d:1)
    at eval (vue-router-tab.umd.min.js?f57d:1)
    at iterator (vue-router.esm.js?8c4f:2225)
    at step (vue-router.esm.js?8c4f:1896)
    at step (vue-router.esm.js?8c4f:1900)
    at step (vue-router.esm.js?8c4f:1900)
    at step (vue-router.esm.js?8c4f:1900)
    at runQueue (vue-router.esm.js?8c4f:1904)
    at HashHistory.confirmTransition (vue-router.esm.js?8c4f:2255)
    at HashHistory.transitionTo (vue-router.esm.js?8c4f:2125)
abort @ vue-router.esm.js?8c4f:2181
iterator @ vue-router.esm.js?8c4f:2251
step @ vue-router.esm.js?8c4f:1896
step @ vue-router.esm.js?8c4f:1900
step @ vue-router.esm.js?8c4f:1900
step @ vue-router.esm.js?8c4f:1900
runQueue @ vue-router.esm.js?8c4f:1904
confirmTransition @ vue-router.esm.js?8c4f:2255
transitionTo @ vue-router.esm.js?8c4f:2125
push @ vue-router.esm.js?8c4f:2595
eval @ vue-router.esm.js?8c4f:2913
push @ vue-router.esm.js?8c4f:2912
logout @ header.vue?24d4:70
handleCommand @ header.vue?24d4:65
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
Vue.$emit @ vue.runtime.esm.js?2b0e:3888
handleMenuItemClick @ element-ui.common.js?5c96:2487
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
Vue.$emit @ vue.runtime.esm.js?2b0e:3888
dispatch @ emitter.js?d010:29
handleClick @ element-ui.common.js?5c96:2774
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6917
vue.runtime.esm.js?2b0e:6900 [Violation] 'click' handler took 268394ms
vue-router.esm.js?8c4f:2146 Uncaught (in promise) TypeError: Cannot read property 'path' of undefined
    at t.get (vue-router-tab.umd.min.js?f57d:1)
    at eval (vue-router-tab.umd.min.js?f57d:1)
    at iterator (vue-router.esm.js?8c4f:2225)
    at step (vue-router.esm.js?8c4f:1896)
    at step (vue-router.esm.js?8c4f:1900)
    at step (vue-router.esm.js?8c4f:1900)
    at step (vue-router.esm.js?8c4f:1900)
    at runQueue (vue-router.esm.js?8c4f:1904)
    at HashHistory.confirmTransition (vue-router.esm.js?8c4f:2255)
    at HashHistory.transitionTo (vue-router.esm.js?8c4f:2125)
<img width="614" alt="截屏2020-07-29 下午11 09 10" src="https://user-images.githubusercontent.com/3301772/88817808-8b70c080-d1f0-11ea-8034-5d436f33daaf.png">

**Comment by bhuh12** [comment]
没能重现该错误，可以提供下重现问题的最简代码吗？方便定位

**Comment by roc0zhang** [comment]
> 没能重现该错误，可以提供下重现问题的最简代码吗？方便定位

```
<template>
<el-container>
    <el-aside style="width: auto;">
      <aside></aside>
    </el-aside>
    <el-main>
      <el-container>
        <el-header><header></header></el-header>
        <el-main><main /></el-main>
      </el-container>
    </el-main>
  </el-container>
</template>
```
```main.js
<template>
  <div>
    <!-- <router-view v-if="this.$route.path"></router-view>
	<router-tab v-else/> -->
<router-tab></router-tab>
  </div>
</template>
```
```header.js
...
<el-dropdown-menu slot="dropdown" style="line-height: 13px;position:absolute;top: 40px ">
								<el-dropdown-item command="logout">注销登录</el-dropdown-item>
							</el-dropdown-menu>
...
logout () {
      this.$router.push({ name: 'login', path: '/login' })
}
```
```router.js
export default [{
    path: '/login',
    component: login,
    name: 'login'
  }, {
    path: '/logout',
    redirect: 'login'
  }, {
    path: '/',
    redirect: 'login'
  },
 {
  path: '/sys',
  component: MainLayout,
  name: 'sys',
  children: [{
    path: '/',
    component: main,
    children: [
      ...RouterTabRoutes,
      {
        path: '/',
        redirect: 'Function'
      },
      {
        path: 'Function',
        component: Function,
        name: 'Function',
        meta: {
          title: '功能管理', // 页签标题
          icon: 'el-icon-setting', // 页签图标，可选
          tips: '这是机构管理页面', // 页签提示，可选，如未设置则跟title一致
          aliveId: 'fullPath', // 路由打开页签规则，可选
          tabClass: 'basicColor'
        }
      },
]
...
},
  {
    path: '*',
    redirect: '404'
  }
]
```

**Comment by bhuh12** [comment]
嵌套路由用错了，component: main 这层删掉，children 直接放上层

**Comment by roc0zhang** [comment]
> 嵌套路由用错了，MainLayout 组件内部没有 `router-view`，是直接子组件引入 `main` 的，这不算嵌套路由
> 
> 方案: `component: main` 这层路由删掉，`children` 直接提到上层
> 
> main 如果代码不复杂的话，没必要单独抽离组件，放 MainLayout 里面就可以。
> 而且 html5 也有 main 标签，用这个做组件名也不合适。

规划是mainlayout下有三种不同显示布局，所以又嵌套了一层router-view,去掉果然好了，谢谢指教
