### ISSUE TITLE
多层嵌套路由导航标签页不生效

### ISSUE THREAD

**Issue by 1306229903** [bhuh12/vue-router-tab#63]
## Bug 描述
我设置了多层嵌套路由，导航标签页还是只根据第一层嵌套的路由变化，访问第二级子层路由的时候没变化，导航标签页还是指向的第一层，请问所有路由只能放到同一级吗？

**Comment by bhuh12** [comment]
RouterTab 控件是有意设计成这样的，只有包含 RouterTab 组件的路由的**直接子路由**才参与生成页签页面，再嵌套的下级路由跟 Vue Router 中一样展现。

试想一下，一个页签页面内部还有**子页签**控制页面展示，并且子页签也需要响应路由，这种场景是必须嵌套路由支持的

所有的页签路由都直接放在同一层会很杂乱，我们可以使用 `...` 展开运算符，将不同模块的路由配置合并引入：

```javascript
// RouterTab 内置路由
import { RouterTabRoutes } from 'vue-router-tab'

const news = [{...}]
const product = [{...}]

const routes = [
  {
    path: '/',
    component: Frame,
    children: [
      ...RouterTabRoutes,
      ...news,
      ...product,
    ]
  }
]
```

_Originally posted by @bhuh12 in https://github.com/bhuh12/vue-router-tab/issues/32#issuecomment-558507640_

**Comment by 1306229903** [comment]
已查询路由元信息文档
