### ISSUE TITLE
如何获取已打开的所有tab信息

### ISSUE THREAD

**Issue by 1306229903** [bhuh12/vue-router-tab#65]
如果想一次性关闭多个标签页，并保留某个标签页不关闭，不对它进行刷新重置，不使用reset这个api
现在思路主要是结合close这个api和打开的tab页个数来循环关闭，现在问题是获取不到当前打开的所有tab页信息

请问有获取当前所有打开的tab页信息对应的api吗？

**Comment by bhuh12** [comment]
`this.$tabs.items` 可以获取当前打开的页签数组

你是需要做类似关闭其他页签的操作吗？这个目前是右键菜单的功能，没有暴露给外部。

**Comment by 1306229903** [comment]
> `this.$tabs.items` 可以获取当前打开的页签数组
> 
> 你是需要做类似关闭其他页签的操作吗？这个目前是右键菜单的功能，没有暴露给外部。

是的，就是关闭其他页签这个需求，最开始试了reset再打开之前保存的页签，但没办法保存原有页签状态，直接刷新了

**Comment by bhuh12** [comment]
`reset` 是为了在用户身份角色更改后重置页签的，场景不一样。
你可以遍历 `this.$tabs.items` ，如果是需要保留的页签就 `$router.replace` 进入，否则强制关闭

**Comment by bhuh12** [comment]
https://bhuh12.gitee.io/vue-router-tab/zh/api/#routertab-items

`routerTab.items`：所有的页签数据
