### ISSUE TITLE
change tab option language

### ISSUE THREAD

**Issue by muzammil17** [bhuh12/vue-router-tab#66]
hello, the issue im facing is that my application default language is english. Since vue router is in Chinese so the issue is that the tab  option menu is in Chinese and i have made alot of changes but the language is not changing and every time i have to translate the page to see options in english. 
![Screenshot (2)](https://user-images.githubusercontent.com/30322831/90597510-b906c380-e20a-11ea-95c4-6c5dcd6f4d52.png)

**Comment by bhuh12** [comment]
<router-tab language="en" />

**Comment by muzammil17** [comment]
i tried but this is not working

![Screenshot (3)](https://user-images.githubusercontent.com/30322831/90613669-21619f00-e223-11ea-8a1b-2aab2a888438.png)
![Screenshot (4)](https://user-images.githubusercontent.com/30322831/90613673-2292cc00-e223-11ea-8682-55199abbf406.png)

**Comment by bhuh12** [comment]
Show me screenshots of vue devtools

![image](https://user-images.githubusercontent.com/9862292/90622934-64823900-e248-11ea-890d-f9c27146327e.png)
