### ISSUE TITLE
Hot reload on latest version of router-tab

### ISSUE THREAD

**Issue by dalholm** [bhuh12/vue-router-tab#69]
**Describe the bug**
Hot reload becomes a blank page. Need to refresh page to load content. 
I updated from 1.0.0-alpha to 1.2.0, are there something i should reconfigure? 

**To Reproduce**
Trigger hot reload

**Comment by bhuh12** [comment]
for BREAKING CHANGES

Reference: https://bhuh12.github.io/vue-router-tab/guide/changelog.html

**Comment by dalholm** [comment]
@bhuh12 all those changes i could make are made as far as i can se. Is there any change in particular that you think could inflict this?

**Comment by bhuh12** [comment]
https://github.com/bhuh12/router-tab-sample

Does the sample project have the same problem when you run it?

**Comment by dalholm** [comment]
@bhuh12 strange, that worked fine. The hardest part is that in my project its very nested. But i suppose i need to refactor and reinstall it. Probably for the best anyways. Thanks for the help @bhuh12

**Comment by bhuh12** [comment]
You can try to update the version of the development dependencies

**Comment by dalholm** [comment]
@bhuh12 what do you mean? :)

**Comment by bhuh12** [comment]
Could you show me `package.json` in your project ?
![image](https://user-images.githubusercontent.com/9862292/91298595-e3d8b500-e7d2-11ea-9701-ea781a589fa4.png)

**Comment by satria1697** [comment]
hi, i got same problem
![image](https://user-images.githubusercontent.com/39475953/106345853-b2b26280-62e5-11eb-8d00-2d0867eae3f8.png)
should i downgrade my vue-router?

**Comment by bhuh12** [comment]
> hi, i got same problem
> ![image](https://user-images.githubusercontent.com/39475953/106345853-b2b26280-62e5-11eb-8d00-2d0867eae3f8.png)
> should i downgrade my vue-router?

Does this problem occur when changing a page component or a sub component of a page

**Comment by satria1697** [comment]
on View, page component

**Comment by bhuh12** [comment]
> on View, page component
> its fine when i change something on Modal or any component, but when i make a change, on View, it become blank

Can you see any error messages on the console?
Does the problem reproduce on the sample project?
https://github.com/bhuh12/router-tab-sample

**Comment by satria1697** [comment]
it is fine if u use a brand new code, but when i use my developed code, it becomes blank

**Comment by bhuh12** [comment]
> it is fine if u use a brand new code, but when i use my developed code, it becomes blank

You can try to delete the node_modules directory and reinstall the dependencies.
