### ISSUE TITLE
多级路由同样会加载标签页栏中，怎么限制不影响

### ISSUE THREAD

**Issue by ydlemon** [bhuh12/vue-router-tab#7]

**Comment by bhuh12** [comment]
需要将共用页签的路由，meta 配置 alive-id 函数，返回相同的字符串。

请参考:
https://bhuh12.github.io/vue-router-tab/guide/essentials/rule.html#路由页签规则

**Comment by jackcailj** [comment]
有同样的问题，希望能尽快更新下，在页签代码中使用routerview，会新打开一个页签，使用alive-id函数方法，会刷新页面

**Comment by bhuh12** [comment]
Vue Router Tab `v0.2.0` 已添加嵌套路由页面支持。
请移除嵌套路由配置的 `aliveId` 方法，使用内置的规则即可

Demo: [https://bhuh12.github.io/vue-router-tab/demo/#/default/nest/1/page1](https://bhuh12.github.io/vue-router-tab/demo/#/default/nest/1/page1)
