### ISSUE TITLE
Max Number of Tabs

### ISSUE THREAD

**Issue by benjwilson10** [bhuh12/vue-router-tab#70]
Hi,

Great work on the package. I see we have 'max-alive' which clears the cache of the earliest opened tabs once the number of tabs exceeds the set value. Is it possible to have an option for 'max-open' (or similar) that behaves the same as max-alive, but actually closes the tabs of the earliest opened.

My users end up having 50+ tabs open and it would be good to limit the total number and close the earliest opened.

Thanks again

**Comment by bhuh12** [comment]
I don’t think it’s a good experience for us to actively close the tabs opened by the user
