### ISSUE TITLE
vue-router-tab component

### ISSUE THREAD

**Issue by mwasigala** [bhuh12/vue-router-tab#73]
When i utilize <router-tab /> i get the following error

 [Vue warn]: Unknown custom element: <router-tab> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by bhuh12** [comment]
https://bhuh12.github.io/vue-router-tab/guide/essentials/#import-routertab

`Vue.use(RouterTab)`

**Comment by mwasigala** [comment]
@bhuh12  i have followed the instructions you provided in your documentation...

**Comment by bhuh12** [comment]
could you submit the simplest code that reproduces the problem to an open git repository (such as Github)

**Comment by mwasigala** [comment]
@bhuh12 

https://github.com/mwasigala/Tabs

**Comment by bhuh12** [comment]
https://github.com/mwasigala/Tabs/pull/1

`Vue.use(VueRouter)`

![image](https://user-images.githubusercontent.com/9862292/92725066-22a76700-f39e-11ea-8775-3353386b1109.png)

**Comment by mwasigala** [comment]
@bhuh12  sorry may be i couldn't replicate the issue properly but with the real project i did define the vue.use(VueRouter) still the same issue

**Comment by bhuh12** [comment]
Please screenshot all error messages

**Comment by mwasigala** [comment]
<img width="403" alt="BaleleError" src="https://user-images.githubusercontent.com/20720317/92750333-a443c880-f38f-11ea-9eb2-d3507aecb7e4.PNG">

**Comment by bhuh12** [comment]
Reference: https://github.com/mwasigala/Tabs/pull/1/files

If the problem is still not resolved, please resubmit the code that reproduces the problem

**Comment by mwasigala** [comment]
its solved
