### ISSUE TITLE
Lifecycle hooks

### ISSUE THREAD

**Issue by mwasigala** [bhuh12/vue-router-tab#75]
what life-cycle hook can i call when the tabs are revisited
  i have a variable in store that i need to update whenever the user revisits the tabs

**Comment by bhuh12** [comment]
`activated`
`deactivated`

https://vuejs.org/v2/api/index.html#keep-alive

**Comment by mwasigala** [comment]
Thanks

**Comment by mwasigala** [comment]
There is another issue if the frame layout is nested in another component the untitled tab appears and then disappears whenever you click in any of the other tabs

**Comment by bhuh12** [comment]
Is there a screenshot ?

**Comment by mwasigala** [comment]
When loaded at first time
<img width="235" alt="vue-router-tab-first-load" src="https://user-images.githubusercontent.com/20720317/93327757-76dd9b80-f823-11ea-8607-61910f7b6319.PNG">


When i click one tab
<img width="249" alt="vue-router-tab-clicked" src="https://user-images.githubusercontent.com/20720317/93327797-85c44e00-f823-11ea-83a9-32d4b8e10137.PNG">

**Comment by bhuh12** [comment]
You need to configure the tab for the route of the default page

**Comment by mwasigala** [comment]
@bhuh12  what do you mean by default page

**Comment by mwasigala** [comment]
I have a component lets say home within component home i used another component  lets call it welcome, inside welcome router-tab is consumed....

**Comment by bhuh12** [comment]
Can you provide the code for routing configuration and component introduction
