### ISSUE TITLE
Routing outside the vue router gives error

### ISSUE THREAD

**Issue by muzammil17** [bhuh12/vue-router-tab#76]
Hey,
Im using vuex and vue router tab in my application. The application is directed to the dashboard and if the user is not Authorized it redirects to the login page. It is generates an error which is unable to understand
![Screenshot (10)](https://user-images.githubusercontent.com/30322831/93659792-9e6e7700-fa62-11ea-9329-615f95070f05.png)

**Comment by bhuh12** [comment]
Can you provide the simplest code to reproduce the problem?

**Comment by muzammil17** [comment]
I cant. I think the error is due to redirect. I have two main pages login and home. Inside my home router there are children routes using vue router tab. If the user is unauthorized it redirects from  vue router tab route to /login it generates this error and if I logout the user it will generate this error. I will try to reproduce the same code and will share with you by tomorrow

**Comment by bhuh12** [comment]
The `v1.2.1` version has been released, please update to see if it solves the problem.

**Comment by muzammil17** [comment]
The issue is solved. Thank you 👍
