### ISSUE TITLE
默认tab设置closable，然后再添加tab时，默认的tab就有了关闭

### ISSUE THREAD

**Issue by gudufy** [bhuh12/vue-router-tab#77]
## Bug 描述

默认tab设置closable，然后再添加tab时，默认的tab就有了关闭。
这是升级到1.2出现的问题

## 问题重现

重现行为的步骤：

1. 增加一个默认tabs
2. router-link一个tab
3. 移动到默认tab
4. 默认tab出现了关闭图标

## 预期行为

设置closable:false的tab任何情况下都不能关闭。

## 截图

![QQ截图20200922151526](https://user-images.githubusercontent.com/117419/93853819-2664b300-fce7-11ea-828c-f7cb6c8ff22f.png)

**Comment by bhuh12** [comment]
需要在路由 meta 里面设置 closable，默认页签里面的设置只是临时的。

如果不是 nuxt，建议直接配置 fullpath：

``` javascript
tabs: [
        // 只需设置 fullpath，程序将自动从 router 配置中获取页签的标题/图标等信息
        '/initial-tabs/page-leave'
]
```
