### ISSUE TITLE
我从版本0.2.9升级到1.2.0，出现下面错误

### ISSUE THREAD

**Issue by SHUAIBEST** [bhuh12/vue-router-tab#81]
![image](https://user-images.githubusercontent.com/16318650/95811679-63502280-0d46-11eb-9c6e-c3289f82d119.png)
![image](https://user-images.githubusercontent.com/16318650/95811771-8f6ba380-0d46-11eb-9d83-86bfca9ae73b.png)。
我登录进来跳到了‘/index’后，在header组件里有一个退出登录，点退出就报错错误了，请问是什么问题导致的？

**Comment by bhuh12** [comment]
能否定义一下错误代码所在行？
![image](https://user-images.githubusercontent.com/9862292/95813039-86c89c80-0d49-11eb-8938-cafa869fa840.png)

**Comment by SHUAIBEST** [comment]
![image](https://user-images.githubusercontent.com/16318650/95815207-c645b780-0d4e-11eb-951e-97fb31cdae56.png)

**Comment by bhuh12** [comment]
没能重现问题发生的场景。
能否贴一下路由相关配置代码？或者提供下重现问题的最简 git 项目？

**Comment by SHUAIBEST** [comment]
项目提供不了，是内部的。路由js就是上面截图的结构。是有参数没设对吗？

**Comment by bhuh12** [comment]
应该跟参数无关，推测是特定路由结构下面的代码运行错误。
需要知道整体的 `routes` 路由配置，我看看根据这个结构是否复现问题。
最好是提供一下能直接运行并复现问题的**最精简**代码（剥离所有业务相关代码）。

**Comment by bhuh12** [comment]
另外，报错有没有阻塞页面功能操作？

**Comment by SHUAIBEST** [comment]
import App from '../App'
import {RouterTabRoutes} from 'vue-router-tab'
import {importPage} from '../utils'


const login = r => require.ensure([], () => r(require('../views/login/LoginIndex')), 'login')
const header = r => require.ensure([], () => r(require('../components/frames/Header')), 'header')
const aside = r => require.ensure([], () => r(require('../components/frames/Aside')), 'aside')


export default [
  {
    path: '/',
    component: App,
    children:
      [{
        path: '/',
        redirect: '/login'
      },{
        path: '/login',
        component: login,
        name: 'login'
      }, {
        path: '/',
        component: header,
        children: [{
          path: '/',
          component: aside,
          children: [
            ...RouterTabRoutes,
            {
              path: '/index',
              component: importPage('index'),
              meta: {
                title: '首页', // 页签标题
                icon: 'icon-user', // 页签图标，可选
                tips: '首页', // 页签提示，可选，如未设置则跟title一致
                key: 'path' // 路由打开页签规则，可选
              }
            },
  

          ]
        }]
      }, {
        path: '/404',
        component: importPage('404'),
        meta: {
          title: '找不到页面',
          icon: 'icon-page'
        }
      }, {
        // 其他路由 404
        path: '*',
        redirect: '/404'
      }]
  }]


这是路由配置，router-tab是aside里的，App->header->router-view->aside->router-tab结构是这样的。header里有一个按钮‘退出登录‘，我退出成功后，是要跳到login路由的，但是报错，页面无变化不跳转。

**Comment by SHUAIBEST** [comment]
而且有一种情况是，我在aside的children有其他路由/baseInfo时，从/index可以跳转/baseInfo，跳/login就出错了

**Comment by bhuh12** [comment]
已经发布了 `v1.2.1` 版本，请更新看看是否解决问题

**Comment by SHUAIBEST** [comment]
升级后没问题了，谢谢！

**Comment by bhuh12** [comment]
不客气
