### ISSUE TITLE
重大问题 vue-router 3.4.6版本更新，去掉param的二次decode会导致严重问题

### ISSUE THREAD

**Issue by StevenLikeWatermelon** [bhuh12/vue-router-tab#82]
## Bug 描述

vue-router 3.4.6为了解决query出现%导致[报错问题](https://github.com/vuejs/vue-router/pull/3323),更新了版本，导致iframe模式下。url以params的形式传递时没有decode，进而导致iframe的src解析失败

## 问题重现

重现行为的步骤：

1.选择iframe模式
2.选择打开任意一个url

## 预期行为

tab页中显示一个iframe

## 实际效果

多个iframe死循环

**Comment by bhuh12** [comment]
死循环的 iframe 原始链接能提供一下吗？

**Comment by bhuh12** [comment]
看如下更改是否能解决问题？

[`/lib/page/Iframe.vue#25`](https://github.com/bhuh12/vue-router-tab/blob/master/lib/page/Iframe.vue)

``` javascript
computed: {
    // 链接安全过滤，避免执行js
    url() {
      let { src } = this

      // XSS 攻击链接返回空白页
      if (/^javascript:/.test(src)) {
        return 'about:blank'
      }

      // 解码已编码的链接
      if (src.includes(encodeURIComponent('://'))) {
        return decodeURIComponent(src)
      }

      return src
    }
  }
```

![image](https://user-images.githubusercontent.com/9862292/96238120-b63d0a80-0fd0-11eb-84da-00f9ddaa865c.png)

**Comment by StevenLikeWatermelon** [comment]
> 看如下更改是否能解决问题？
> 
> [fix(iframe): 解决 vue-router 3.4.6 params 中的链接未解码导致 iframe 页签加载失败](https://github.com/bhuh12/vue-router-tab/commit/c083950147f236da527eaa3fb3a91cc435b40f2b)
> 
> ```js
> computed: {
>     // 链接安全过滤，避免执行js
>     url() {
>       let { src } = this
> 
>       // XSS 攻击链接返回空白页
>       if (/^javascript:/.test(src)) {
>         return 'about:blank'
>       }
> 
>       return decodeURIComponent(src)
>     }
>   }
> ```
> 
> ![image](https://user-images.githubusercontent.com/9862292/96238120-b63d0a80-0fd0-11eb-84da-00f9ddaa865c.png)

恩，这样应该是可以的，感谢！

**Comment by StevenLikeWatermelon** [comment]
> 死循环的 iframe 原始链接能提供一下吗？

任意一个 完整的网址都可以复现

**Comment by bhuh12** [comment]
已经发布了 `v1.2.1` 版本，请更新看看是否解决问题

**Comment by StevenLikeWatermelon** [comment]
> 已经发布了 `v1.2.1` 版本，请更新看看是否解决问题

1.2.1已经解决该问题。非常感谢！
