### ISSUE TITLE
Passing Props

### ISSUE THREAD

**Issue by mwasigala** [bhuh12/vue-router-tab#85]
Using default tabs configuration

props cannot be passed to individual tabs
it says undefined
below is the template i used to add default tabs, the tabs are added but the props are undefined

{ to: { name: "componentname", params: { data: this.data} } }

**Comment by bhuh12** [comment]
`to` is used to set the access route when the tab is activated。
You should check the value of ` this.data `.

**Comment by mwasigala** [comment]
this.data is a json string...

How does one pass props to the tabs?!

**Comment by bhuh12** [comment]
which props?

**Comment by mwasigala** [comment]
how to pass data from the frame to the tabs

i have a json data and i want to pass it to one of the tabs

**Comment by bhuh12** [comment]
Maybe you need vuex

**Comment by mwasigala** [comment]
i do not need the vuex store..  for now..
What i want is to pass data to the component which is one of the tabs,
is it possible for me to pass data using props of the vue component or not?

**Comment by bhuh12** [comment]
Through the meta route, we can configure the title, icon, prompt and cache rule of a route tab.
https://bhuh12.github.io/vue-router-tab/api/#route-meta
