### ISSUE TITLE
Find out if tab is active from within tab

### ISSUE THREAD

**Issue by ithil** [bhuh12/vue-router-tab#86]
Hey, I really like this component, thank you for all your work! :)  
However there is one thing I haven't been able to accomplish yet:

**Is your feature request related to a problem? Please describe.**
I'm trying to render a portal but only if the tab containing the portal is currently active. The portal points to a status bar in the parent component (which also contains the `<router-tab />`). In the status bar widgets are supposed to be rendered from within the current tab. That works well but in order to hide them when the tab is no longer active I need to find out whether it is active or not.

To find out if the tab is currently active I tried `this.$route.path == this.$tabs.activeTab.to` but this seems to be always true. 🤔 

**Describe the solution you'd like**
Is there any way to find out if a tab/route is currently active from within a component? Or maybe a way to find out the id of the tab from within the component, then I could do `this.$tabs.activeTabId == this.$tabs.thisTabId` or something similar.

**Comment by bhuh12** [comment]
`this.$route.path === portalPath`

**Comment by ithil** [comment]
> `this.$route.path === portalPath`

Thank you for your quick answer! However, I don't quite understand how to use it. Where do I get the `portalPath` from?

To be more clear, the portal target is outside of the router-tab, my App.vue looks like this:
```vue
<template>
...
      <div>
        <router-tab lang="en"/>
        <div id="statusBar">
          <portal-target name="statusBarLeft" multiple />
          <portal-target name="statusBarRight" multiple />
        </div>
      </div>
...
</template>
```

And the portal (inside the component called `Editor.vue`) looks like this:
```vue
<template>
  <div>
...
      <div>
        <portal to="statusBarRight" :order="1" v-if="portalActive">
          <span class="widget">{{widgetContent}}</span>
        </portal>
      </div>
  </div>
</template>
```
And `portalActive` is the computed property where I had put `this.$route.path == this.$tabs.activeTab.to` without success.

Hardcoding the path in the component is also not really an option because the path is dynamic:
```javascript
...
  {
    path: '/editor/:id',
    name: 'Editor',
    component: Editor,
    meta: {
      title: 'Editor', // tab title
      key: 'path',
      closable: true // is tab closable, defaults to `true`
    },
  },
...
```

**Comment by bhuh12** [comment]
`this.$route.name === 'Editor'`

**Comment by ithil** [comment]
This doesn't work because there can be (and often are) multiple editor tabs opening different texts and they all render their respective widgets through the portal (so the widgets from all the editor tabs are shown simultaneously).

However, I found a different solution to my particular problem using Vue's `activated` and `deactivated` hooks:
```javascript
...
  activated() {
    this.portalActive = true
  },
  deactivated() {
    this.portalActive = false
  },
  data() {
    return {
      portalActive: true,
    }
  },
...
```
Thank you for your help! :)
