### ISSUE TITLE
可否支持根据参数不同新开多个tab呢

### ISSUE THREAD

**Issue by ryanypm** [bhuh12/vue-router-tab#93]
## 您的需求是否与问题有关？
是
同一个路由会被覆盖

## 描述你想要的解决方案
同一个路由如果参数不同支持新开tab
如：[文章列表]-[详情详情id1]-[文章详情id2]

**Comment by bhuh12** [comment]
https://bhuh12.gitee.io/vue-router-tab/zh/guide/advanced/cache.html#%E9%A1%B5%E7%AD%BE%E8%A7%84%E5%88%99
```
const route = {
  path: '/my-page/:id',
  component: MyPage,
  meta: {
    title: route => `页面${route.params.id}`,
    key: 'fullPath'
  }
}
```
