### ISSUE TITLE
为何每次刷新，都会保留刷新之前的最后一个页签啊

### ISSUE THREAD

**Issue by ycmoon** [bhuh12/vue-router-tab#95]
我增加了一个首页，在页面Created中Push到路由中，再打开几个新页签后，点击刷新后，最后一个打开的激活新签还是保留了，请问要怎么设置，参数中没看到相应设置。

**Comment by bhuh12** [comment]
是刷新单个页签、刷新全部页签，还是浏览器的刷新？

**Comment by ycmoon** [comment]
浏览器刷新

**Comment by bhuh12** [comment]
打开哪个页签是根据当前访问路由来确定的。
你是需要刷新后在同一个路由页面但不要页签？这样前后不一致不会很奇怪吗？

**Comment by ycmoon** [comment]
我是想不论当前打开多少个页签，当前是哪个页签，浏览器刷新后，只保留默认的首页页签，

**Comment by bhuh12** [comment]
你是希望刷新后直接进入首页？
可以尝试在Vue Router 的[全局前置守卫导航](https://router.vuejs.org/zh/guide/advanced/navigation-guards.html#%E5%85%A8%E5%B1%80%E5%89%8D%E7%BD%AE%E5%AE%88%E5%8D%AB)里控制一下，如果首次进入直接跳转首页的路由

**Comment by ycmoon** [comment]
我目前是用户登录后，进入首页的路由，如果在守卫中再加一个，岂不是成了死循环

**Comment by bhuh12** [comment]
判断限制一下就好，如果当前就是首页为啥还跳转？

**Comment by ycmoon** [comment]
还是一样，刷新后除首页页签外，还有刷新前的页签。

刷新后，我看到Session Storage中的值，还是两个页签的数据。

**Comment by bhuh12** [comment]
你开启了 restore 刷新后还原页签吗？如果你需要第一次进首页，还开启这个干嘛?
