### ISSUE TITLE
vue 2.5.22 tab-item报错

### ISSUE THREAD

**Issue by serializedowen** [bhuh12/vue-router-tab#97]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Development Environment (please complete the following information):**

- Node.js: [e.g. v12.4.0]
- Vue: [e.g. v2.5.22]
- Vue Router [e.g. v3.0.1]
- **Vue Router Tab** [e.g. v0.2.0]

**Operating Environment (please complete the following information):**

- Device: [e.g. Desktop]
- OS: [e.g. Windows 10]
- Browser [e.g. stock browser, Chrome]
- Version [e.g. 75]

**Additional context**

![image](https://user-images.githubusercontent.com/9219215/101757918-b52ce300-3b12-11eb-9326-3ec935958b3b.png)
![image](https://user-images.githubusercontent.com/9219215/101758042-d5f53880-3b12-11eb-8c10-948d38f37174.png)

图中为vue.esm.js中的resolveScopedSlots 方法
上图为vue2.6.x  下图为vue2.5.x    2.5中未处理scopedSlot返回null的情况，导致TabItem无法渲染。

**Comment by bhuh12** [comment]
低版本的 vue 模板编译 slot插槽方式不一样。你先将 `package.json` 的 `vue-template-compiler` 依赖版本改成这个试试：

``` json
{
  "devDependencies": {
    "vue-template-compiler": "^2.6.10"
  }
}
```

_Originally posted by @bhuh12 in https://github.com/bhuh12/vue-router-tab/issues/61#issuecomment-655963647_

**Comment by serializedowen** [comment]
嗯嗯 改了是可以。。我是觉得本身可以做下适配  毕竟写着是兼容2.5的

**Comment by bhuh12** [comment]
该问题已在 `v1.2.3` 版本修复，欢迎更新验证

更新日志：
https://bhuh12.gitee.io/vue-router-tab/zh/guide/changelog.html
